#ifndef STM32L432KC_PWR_H
#define STM32L432KC_PWR_H

#include <stdint.h>

#define ALL1 ( (uint32_t) 0xFFFFFFFF )

typedef struct {
    uint32_t CR1;
    uint32_t CR2;
    uint32_t CR3;
    uint32_t CR4;
    uint32_t SR1;
    uint32_t SR2;
    uint32_t SCR;
    uint32_t RESERVED0;
    uint32_t PUCRA;
    uint32_t PDCRA;
    uint32_t PUCRB;
    uint32_t PDCRB;
    uint32_t PUCRC;
    uint32_t PDCRC;
    uint32_t PUCRE;
    uint32_t PDCRE;
    uint32_t RESERVED1[4];
    uint32_t PUCRH;
    uint32_t PDCRH;
} PWR_REG_BLOCKS;

/* PWR registers as structs */

#define PWR ( (PWR_REG_BLOCKS volatile *) 0x40007000 )

/* PWR CR1 register macros */

#define PWR_CR1_LPMS(v) ( ( (v) & 0x7 ) << 0 )
#define PWR_CR1_LPMS_MASK PWR_CR1_LPMS(ALL1)
#define PWR_CR1_DBP(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_CR1_DBP_MASK PWR_CR1_DBP(ALL1)
#define PWR_CR1_VOS(v) ( ( (v) & 0x3 ) << 9 )
#define PWR_CR1_VOS_MASK PWR_CR1_VOS(ALL1)
#define PWR_CR1_LPR(v) ( ( (v) & 0x1 ) << 14 )
#define PWR_CR1_LPR_MASK PWR_CR1_LPR(ALL1)

/* PWR CR2 register macros */

#define PWR_CR2_PVDE(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_CR2_PVDE_MASK PWR_CR2_PVDE(ALL1)
#define PWR_CR2_PLS(v) ( ( (v) & 0x7 ) << 1 )
#define PWR_CR2_PLS_MASK PWR_CR2_PLS(ALL1)
#define PWR_CR2_PVME1(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_CR2_PVME1_MASK PWR_CR2_PVME1(ALL1)
#define PWR_CR2_PVME3(v) ( ( (v) & 0x1 ) << 6 )
#define PWR_CR2_PVME3_MASK PWR_CR2_PVME3(ALL1)
#define PWR_CR2_PVME4(v) ( ( (v) & 0x1 ) << 7 )
#define PWR_CR2_PVME4_MASK PWR_CR2_PVME4(ALL1)
#define PWR_CR2_USV(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_CR2_USV_MASK PWR_CR2_USV(ALL1)

/* PWR CR3 register macros */

#define PWR_CR3_EWUP1(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_CR3_EWUP1_MASK PWR_CR3_EWUP1(ALL1)
#define PWR_CR3_EWUP2(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_CR3_EWUP2_MASK PWR_CR3_EWUP2(ALL1)
#define PWR_CR3_EWUP3(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_CR3_EWUP3_MASK PWR_CR3_EWUP3(ALL1)
#define PWR_CR3_EWUP4(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_CR3_EWUP4_MASK PWR_CR3_EWUP4(ALL1)
#define PWR_CR3_EWUP5(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_CR3_EWUP5_MASK PWR_CR3_EWUP5(ALL1)
#define PWR_CR3_RRS(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_CR3_RRS_MASK PWR_CR3_RRS(ALL1)
#define PWR_CR3_APC(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_CR3_APC_MASK PWR_CR3_APC(ALL1)
#define PWR_CR3_ENULP(v) ( ( (v) & 0x1 ) << 11 )
#define PWR_CR3_ENULP_MASK PWR_CR3_ENULP(ALL1)
#define PWR_CR3_EIWUL(v) ( ( (v) & 0x1 ) << 15 )
#define PWR_CR3_EIWUL_MASK PWR_CR3_EIWUL(ALL1)

/* PWR CR4 register macros */

#define PWR_CR4_WP1(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_CR4_WP1_MASK PWR_CR4_WP1(ALL1)
#define PWR_CR4_WP2(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_CR4_WP2_MASK PWR_CR4_WP2(ALL1)
#define PWR_CR4_WP3(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_CR4_WP3_MASK PWR_CR4_WP3(ALL1)
#define PWR_CR4_WP4(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_CR4_WP4_MASK PWR_CR4_WP4(ALL1)
#define PWR_CR4_WP5(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_CR4_WP5_MASK PWR_CR4_WP5(ALL1)
#define PWR_CR4_VBE(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_CR4_VBE_MASK PWR_CR4_VBE(ALL1)
#define PWR_CR4_VBRS(v) ( ( (v) & 0x1 ) << 9 )
#define PWR_CR4_VBRS_MASK PWR_CR4_VBRS(ALL1)
#define PWR_CR4_EXT_SMPS_ON(v) ( ( (v) & 0x1 ) << 13 )
#define PWR_CR4_EXT_SMPS_ON_MASK PWR_CR4_EXT_SMPS_ON(ALL1)

/* PWR SR1 register macros */

#define PWR_SR1_WUF1(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_SR1_WUF1_MASK PWR_SR1_WUF1(ALL1)
#define PWR_SR1_WUF2(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_SR1_WUF2_MASK PWR_SR1_WUF2(ALL1)
#define PWR_SR1_WUF3(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_SR1_WUF3_MASK PWR_SR1_WUF3(ALL1)
#define PWR_SR1_WUF4(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_SR1_WUF4_MASK PWR_SR1_WUF4(ALL1)
#define PWR_SR1_WUF5(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_SR1_WUF5_MASK PWR_SR1_WUF5(ALL1)
#define PWR_SR1_SBF(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_SR1_SBF_MASK PWR_SR1_SBF(ALL1)
#define PWR_SR1_EXT_SMPS_RDY(v) ( ( (v) & 0x1 ) << 13 )
#define PWR_SR1_EXT_SMPS_RDY_MASK PWR_SR1_EXT_SMPS_RDY(ALL1)
#define PWR_SR1_WUFI(v) ( ( (v) & 0x1 ) << 15 )
#define PWR_SR1_WUFI_MASK PWR_SR1_WUFI(ALL1)

/* PWR SR2 register macros */

#define PWR_SR2_REGLPS(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_SR2_REGLPS_MASK PWR_SR2_REGLPS(ALL1)
#define PWR_SR2_REGLPF(v) ( ( (v) & 0x1 ) << 9 )
#define PWR_SR2_REGLPF_MASK PWR_SR2_REGLPF(ALL1)
#define PWR_SR2_VOSF(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_SR2_VOSF_MASK PWR_SR2_VOSF(ALL1)
#define PWR_SR2_PVDO(v) ( ( (v) & 0x1 ) << 11 )
#define PWR_SR2_PVDO_MASK PWR_SR2_PVDO(ALL1)
#define PWR_SR2_PVMO1(v) ( ( (v) & 0x1 ) << 12 )
#define PWR_SR2_PVMO1_MASK PWR_SR2_PVMO1(ALL1)
#define PWR_SR2_PVMO3(v) ( ( (v) & 0x1 ) << 14 )
#define PWR_SR2_PVMO3_MASK PWR_SR2_PVMO3(ALL1)
#define PWR_SR2_PVMO4(v) ( ( (v) & 0x1 ) << 15 )
#define PWR_SR2_PVMO4_MASK PWR_SR2_PVMO4(ALL1)

/* PWR SCR register macros */

#define PWR_SCR_CWUF1(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_SCR_CWUF1_MASK PWR_SCR_CWUF1(ALL1)
#define PWR_SCR_CWUF2(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_SCR_CWUF2_MASK PWR_SCR_CWUF2(ALL1)
#define PWR_SCR_CWUF3(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_SCR_CWUF3_MASK PWR_SCR_CWUF3(ALL1)
#define PWR_SCR_CWUF4(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_SCR_CWUF4_MASK PWR_SCR_CWUF4(ALL1)
#define PWR_SCR_CWUF5(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_SCR_CWUF5_MASK PWR_SCR_CWUF5(ALL1)
#define PWR_SCR_CSBF(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_SCR_CSBF_MASK PWR_SCR_CSBF(ALL1)

/* PWR PUCRA register macros */

#define PWR_PUCRA_PU0(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_PUCRA_PU0_MASK PWR_PUCRA_PU0(ALL1)
#define PWR_PUCRA_PU1(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_PUCRA_PU1_MASK PWR_PUCRA_PU1(ALL1)
#define PWR_PUCRA_PU2(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_PUCRA_PU2_MASK PWR_PUCRA_PU2(ALL1)
#define PWR_PUCRA_PU3(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_PUCRA_PU3_MASK PWR_PUCRA_PU3(ALL1)
#define PWR_PUCRA_PU4(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_PUCRA_PU4_MASK PWR_PUCRA_PU4(ALL1)
#define PWR_PUCRA_PU5(v) ( ( (v) & 0x1 ) << 5 )
#define PWR_PUCRA_PU5_MASK PWR_PUCRA_PU5(ALL1)
#define PWR_PUCRA_PU6(v) ( ( (v) & 0x1 ) << 6 )
#define PWR_PUCRA_PU6_MASK PWR_PUCRA_PU6(ALL1)
#define PWR_PUCRA_PU7(v) ( ( (v) & 0x1 ) << 7 )
#define PWR_PUCRA_PU7_MASK PWR_PUCRA_PU7(ALL1)
#define PWR_PUCRA_PU8(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_PUCRA_PU8_MASK PWR_PUCRA_PU8(ALL1)
#define PWR_PUCRA_PU9(v) ( ( (v) & 0x1 ) << 9 )
#define PWR_PUCRA_PU9_MASK PWR_PUCRA_PU9(ALL1)
#define PWR_PUCRA_PU10(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_PUCRA_PU10_MASK PWR_PUCRA_PU10(ALL1)
#define PWR_PUCRA_PU11(v) ( ( (v) & 0x1 ) << 11 )
#define PWR_PUCRA_PU11_MASK PWR_PUCRA_PU11(ALL1)
#define PWR_PUCRA_PU12(v) ( ( (v) & 0x1 ) << 12 )
#define PWR_PUCRA_PU12_MASK PWR_PUCRA_PU12(ALL1)
#define PWR_PUCRA_PU13(v) ( ( (v) & 0x1 ) << 13 )
#define PWR_PUCRA_PU13_MASK PWR_PUCRA_PU13(ALL1)
#define PWR_PUCRA_PU15(v) ( ( (v) & 0x1 ) << 15 )
#define PWR_PUCRA_PU15_MASK PWR_PUCRA_PU15(ALL1)

/* PWR PDCRA register macros */

#define PWR_PDCRA_PD0(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_PDCRA_PD0_MASK PWR_PDCRA_PD0(ALL1)
#define PWR_PDCRA_PD1(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_PDCRA_PD1_MASK PWR_PDCRA_PD1(ALL1)
#define PWR_PDCRA_PD2(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_PDCRA_PD2_MASK PWR_PDCRA_PD2(ALL1)
#define PWR_PDCRA_PD3(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_PDCRA_PD3_MASK PWR_PDCRA_PD3(ALL1)
#define PWR_PDCRA_PD4(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_PDCRA_PD4_MASK PWR_PDCRA_PD4(ALL1)
#define PWR_PDCRA_PD5(v) ( ( (v) & 0x1 ) << 5 )
#define PWR_PDCRA_PD5_MASK PWR_PDCRA_PD5(ALL1)
#define PWR_PDCRA_PD6(v) ( ( (v) & 0x1 ) << 6 )
#define PWR_PDCRA_PD6_MASK PWR_PDCRA_PD6(ALL1)
#define PWR_PDCRA_PD7(v) ( ( (v) & 0x1 ) << 7 )
#define PWR_PDCRA_PD7_MASK PWR_PDCRA_PD7(ALL1)
#define PWR_PDCRA_PD8(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_PDCRA_PD8_MASK PWR_PDCRA_PD8(ALL1)
#define PWR_PDCRA_PD9(v) ( ( (v) & 0x1 ) << 9 )
#define PWR_PDCRA_PD9_MASK PWR_PDCRA_PD9(ALL1)
#define PWR_PDCRA_PD10(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_PDCRA_PD10_MASK PWR_PDCRA_PD10(ALL1)
#define PWR_PDCRA_PD11(v) ( ( (v) & 0x1 ) << 11 )
#define PWR_PDCRA_PD11_MASK PWR_PDCRA_PD11(ALL1)
#define PWR_PDCRA_PD12(v) ( ( (v) & 0x1 ) << 12 )
#define PWR_PDCRA_PD12_MASK PWR_PDCRA_PD12(ALL1)
#define PWR_PDCRA_PD14(v) ( ( (v) & 0x1 ) << 14 )
#define PWR_PDCRA_PD14_MASK PWR_PDCRA_PD14(ALL1)

/* PWR PUCRB register macros */

#define PWR_PUCRB_PU0(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_PUCRB_PU0_MASK PWR_PUCRB_PU0(ALL1)
#define PWR_PUCRB_PU1(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_PUCRB_PU1_MASK PWR_PUCRB_PU1(ALL1)
#define PWR_PUCRB_PU2(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_PUCRB_PU2_MASK PWR_PUCRB_PU2(ALL1)
#define PWR_PUCRB_PU3(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_PUCRB_PU3_MASK PWR_PUCRB_PU3(ALL1)
#define PWR_PUCRB_PU4(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_PUCRB_PU4_MASK PWR_PUCRB_PU4(ALL1)
#define PWR_PUCRB_PU5(v) ( ( (v) & 0x1 ) << 5 )
#define PWR_PUCRB_PU5_MASK PWR_PUCRB_PU5(ALL1)
#define PWR_PUCRB_PU6(v) ( ( (v) & 0x1 ) << 6 )
#define PWR_PUCRB_PU6_MASK PWR_PUCRB_PU6(ALL1)
#define PWR_PUCRB_PU7(v) ( ( (v) & 0x1 ) << 7 )
#define PWR_PUCRB_PU7_MASK PWR_PUCRB_PU7(ALL1)
#define PWR_PUCRB_PU8(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_PUCRB_PU8_MASK PWR_PUCRB_PU8(ALL1)
#define PWR_PUCRB_PU9(v) ( ( (v) & 0x1 ) << 9 )
#define PWR_PUCRB_PU9_MASK PWR_PUCRB_PU9(ALL1)
#define PWR_PUCRB_PU10(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_PUCRB_PU10_MASK PWR_PUCRB_PU10(ALL1)
#define PWR_PUCRB_PU11(v) ( ( (v) & 0x1 ) << 11 )
#define PWR_PUCRB_PU11_MASK PWR_PUCRB_PU11(ALL1)
#define PWR_PUCRB_PU12(v) ( ( (v) & 0x1 ) << 12 )
#define PWR_PUCRB_PU12_MASK PWR_PUCRB_PU12(ALL1)
#define PWR_PUCRB_PU13(v) ( ( (v) & 0x1 ) << 13 )
#define PWR_PUCRB_PU13_MASK PWR_PUCRB_PU13(ALL1)
#define PWR_PUCRB_PU14(v) ( ( (v) & 0x1 ) << 14 )
#define PWR_PUCRB_PU14_MASK PWR_PUCRB_PU14(ALL1)
#define PWR_PUCRB_PU15(v) ( ( (v) & 0x1 ) << 15 )
#define PWR_PUCRB_PU15_MASK PWR_PUCRB_PU15(ALL1)

/* PWR PDCRB register macros */

#define PWR_PDCRB_PD0(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_PDCRB_PD0_MASK PWR_PDCRB_PD0(ALL1)
#define PWR_PDCRB_PD1(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_PDCRB_PD1_MASK PWR_PDCRB_PD1(ALL1)
#define PWR_PDCRB_PD2(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_PDCRB_PD2_MASK PWR_PDCRB_PD2(ALL1)
#define PWR_PDCRB_PD3(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_PDCRB_PD3_MASK PWR_PDCRB_PD3(ALL1)
#define PWR_PDCRB_PD5(v) ( ( (v) & 0x1 ) << 5 )
#define PWR_PDCRB_PD5_MASK PWR_PDCRB_PD5(ALL1)
#define PWR_PDCRB_PD6(v) ( ( (v) & 0x1 ) << 6 )
#define PWR_PDCRB_PD6_MASK PWR_PDCRB_PD6(ALL1)
#define PWR_PDCRB_PD7(v) ( ( (v) & 0x1 ) << 7 )
#define PWR_PDCRB_PD7_MASK PWR_PDCRB_PD7(ALL1)
#define PWR_PDCRB_PD8(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_PDCRB_PD8_MASK PWR_PDCRB_PD8(ALL1)
#define PWR_PDCRB_PD9(v) ( ( (v) & 0x1 ) << 9 )
#define PWR_PDCRB_PD9_MASK PWR_PDCRB_PD9(ALL1)
#define PWR_PDCRB_PD10(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_PDCRB_PD10_MASK PWR_PDCRB_PD10(ALL1)
#define PWR_PDCRB_PD11(v) ( ( (v) & 0x1 ) << 11 )
#define PWR_PDCRB_PD11_MASK PWR_PDCRB_PD11(ALL1)
#define PWR_PDCRB_PD12(v) ( ( (v) & 0x1 ) << 12 )
#define PWR_PDCRB_PD12_MASK PWR_PDCRB_PD12(ALL1)
#define PWR_PDCRB_PD13(v) ( ( (v) & 0x1 ) << 13 )
#define PWR_PDCRB_PD13_MASK PWR_PDCRB_PD13(ALL1)
#define PWR_PDCRB_PD14(v) ( ( (v) & 0x1 ) << 14 )
#define PWR_PDCRB_PD14_MASK PWR_PDCRB_PD14(ALL1)
#define PWR_PDCRB_PD15(v) ( ( (v) & 0x1 ) << 15 )
#define PWR_PDCRB_PD15_MASK PWR_PDCRB_PD15(ALL1)

/* PWR PUCRC register macros */

#define PWR_PUCRC_PU0(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_PUCRC_PU0_MASK PWR_PUCRC_PU0(ALL1)
#define PWR_PUCRC_PU1(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_PUCRC_PU1_MASK PWR_PUCRC_PU1(ALL1)
#define PWR_PUCRC_PU2(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_PUCRC_PU2_MASK PWR_PUCRC_PU2(ALL1)
#define PWR_PUCRC_PU3(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_PUCRC_PU3_MASK PWR_PUCRC_PU3(ALL1)
#define PWR_PUCRC_PU4(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_PUCRC_PU4_MASK PWR_PUCRC_PU4(ALL1)
#define PWR_PUCRC_PU5(v) ( ( (v) & 0x1 ) << 5 )
#define PWR_PUCRC_PU5_MASK PWR_PUCRC_PU5(ALL1)
#define PWR_PUCRC_PU6(v) ( ( (v) & 0x1 ) << 6 )
#define PWR_PUCRC_PU6_MASK PWR_PUCRC_PU6(ALL1)
#define PWR_PUCRC_PU7(v) ( ( (v) & 0x1 ) << 7 )
#define PWR_PUCRC_PU7_MASK PWR_PUCRC_PU7(ALL1)
#define PWR_PUCRC_PU8(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_PUCRC_PU8_MASK PWR_PUCRC_PU8(ALL1)
#define PWR_PUCRC_PU9(v) ( ( (v) & 0x1 ) << 9 )
#define PWR_PUCRC_PU9_MASK PWR_PUCRC_PU9(ALL1)
#define PWR_PUCRC_PU10(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_PUCRC_PU10_MASK PWR_PUCRC_PU10(ALL1)
#define PWR_PUCRC_PU11(v) ( ( (v) & 0x1 ) << 11 )
#define PWR_PUCRC_PU11_MASK PWR_PUCRC_PU11(ALL1)
#define PWR_PUCRC_PU12(v) ( ( (v) & 0x1 ) << 12 )
#define PWR_PUCRC_PU12_MASK PWR_PUCRC_PU12(ALL1)
#define PWR_PUCRC_PU13(v) ( ( (v) & 0x1 ) << 13 )
#define PWR_PUCRC_PU13_MASK PWR_PUCRC_PU13(ALL1)
#define PWR_PUCRC_PU14(v) ( ( (v) & 0x1 ) << 14 )
#define PWR_PUCRC_PU14_MASK PWR_PUCRC_PU14(ALL1)
#define PWR_PUCRC_PU15(v) ( ( (v) & 0x1 ) << 15 )
#define PWR_PUCRC_PU15_MASK PWR_PUCRC_PU15(ALL1)

/* PWR PDCRC register macros */

#define PWR_PDCRC_PD0(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_PDCRC_PD0_MASK PWR_PDCRC_PD0(ALL1)
#define PWR_PDCRC_PD1(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_PDCRC_PD1_MASK PWR_PDCRC_PD1(ALL1)
#define PWR_PDCRC_PD2(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_PDCRC_PD2_MASK PWR_PDCRC_PD2(ALL1)
#define PWR_PDCRC_PD3(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_PDCRC_PD3_MASK PWR_PDCRC_PD3(ALL1)
#define PWR_PDCRC_PD4(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_PDCRC_PD4_MASK PWR_PDCRC_PD4(ALL1)
#define PWR_PDCRC_PD5(v) ( ( (v) & 0x1 ) << 5 )
#define PWR_PDCRC_PD5_MASK PWR_PDCRC_PD5(ALL1)
#define PWR_PDCRC_PD6(v) ( ( (v) & 0x1 ) << 6 )
#define PWR_PDCRC_PD6_MASK PWR_PDCRC_PD6(ALL1)
#define PWR_PDCRC_PD7(v) ( ( (v) & 0x1 ) << 7 )
#define PWR_PDCRC_PD7_MASK PWR_PDCRC_PD7(ALL1)
#define PWR_PDCRC_PD8(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_PDCRC_PD8_MASK PWR_PDCRC_PD8(ALL1)
#define PWR_PDCRC_PD9(v) ( ( (v) & 0x1 ) << 9 )
#define PWR_PDCRC_PD9_MASK PWR_PDCRC_PD9(ALL1)
#define PWR_PDCRC_PD10(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_PDCRC_PD10_MASK PWR_PDCRC_PD10(ALL1)
#define PWR_PDCRC_PD11(v) ( ( (v) & 0x1 ) << 11 )
#define PWR_PDCRC_PD11_MASK PWR_PDCRC_PD11(ALL1)
#define PWR_PDCRC_PD12(v) ( ( (v) & 0x1 ) << 12 )
#define PWR_PDCRC_PD12_MASK PWR_PDCRC_PD12(ALL1)
#define PWR_PDCRC_PD13(v) ( ( (v) & 0x1 ) << 13 )
#define PWR_PDCRC_PD13_MASK PWR_PDCRC_PD13(ALL1)
#define PWR_PDCRC_PD14(v) ( ( (v) & 0x1 ) << 14 )
#define PWR_PDCRC_PD14_MASK PWR_PDCRC_PD14(ALL1)
#define PWR_PDCRC_PD15(v) ( ( (v) & 0x1 ) << 15 )
#define PWR_PDCRC_PD15_MASK PWR_PDCRC_PD15(ALL1)

/* PWR PUCRD register macros */

#define PWR_PUCRD_PU0(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_PUCRD_PU0_MASK PWR_PUCRD_PU0(ALL1)
#define PWR_PUCRD_PU1(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_PUCRD_PU1_MASK PWR_PUCRD_PU1(ALL1)
#define PWR_PUCRD_PU2(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_PUCRD_PU2_MASK PWR_PUCRD_PU2(ALL1)
#define PWR_PUCRD_PU3(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_PUCRD_PU3_MASK PWR_PUCRD_PU3(ALL1)
#define PWR_PUCRD_PU4(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_PUCRD_PU4_MASK PWR_PUCRD_PU4(ALL1)
#define PWR_PUCRD_PU5(v) ( ( (v) & 0x1 ) << 5 )
#define PWR_PUCRD_PU5_MASK PWR_PUCRD_PU5(ALL1)
#define PWR_PUCRD_PU6(v) ( ( (v) & 0x1 ) << 6 )
#define PWR_PUCRD_PU6_MASK PWR_PUCRD_PU6(ALL1)
#define PWR_PUCRD_PU7(v) ( ( (v) & 0x1 ) << 7 )
#define PWR_PUCRD_PU7_MASK PWR_PUCRD_PU7(ALL1)
#define PWR_PUCRD_PU8(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_PUCRD_PU8_MASK PWR_PUCRD_PU8(ALL1)
#define PWR_PUCRD_PU9(v) ( ( (v) & 0x1 ) << 9 )
#define PWR_PUCRD_PU9_MASK PWR_PUCRD_PU9(ALL1)
#define PWR_PUCRD_PU10(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_PUCRD_PU10_MASK PWR_PUCRD_PU10(ALL1)
#define PWR_PUCRD_PU11(v) ( ( (v) & 0x1 ) << 11 )
#define PWR_PUCRD_PU11_MASK PWR_PUCRD_PU11(ALL1)
#define PWR_PUCRD_PU12(v) ( ( (v) & 0x1 ) << 12 )
#define PWR_PUCRD_PU12_MASK PWR_PUCRD_PU12(ALL1)
#define PWR_PUCRD_PU13(v) ( ( (v) & 0x1 ) << 13 )
#define PWR_PUCRD_PU13_MASK PWR_PUCRD_PU13(ALL1)
#define PWR_PUCRD_PU14(v) ( ( (v) & 0x1 ) << 14 )
#define PWR_PUCRD_PU14_MASK PWR_PUCRD_PU14(ALL1)
#define PWR_PUCRD_PU15(v) ( ( (v) & 0x1 ) << 15 )
#define PWR_PUCRD_PU15_MASK PWR_PUCRD_PU15(ALL1)

/* PWR PDCRD register macros */

#define PWR_PDCRD_PD0(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_PDCRD_PD0_MASK PWR_PDCRD_PD0(ALL1)
#define PWR_PDCRD_PD1(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_PDCRD_PD1_MASK PWR_PDCRD_PD1(ALL1)
#define PWR_PDCRD_PD2(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_PDCRD_PD2_MASK PWR_PDCRD_PD2(ALL1)
#define PWR_PDCRD_PD3(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_PDCRD_PD3_MASK PWR_PDCRD_PD3(ALL1)
#define PWR_PDCRD_PD4(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_PDCRD_PD4_MASK PWR_PDCRD_PD4(ALL1)
#define PWR_PDCRD_PD5(v) ( ( (v) & 0x1 ) << 5 )
#define PWR_PDCRD_PD5_MASK PWR_PDCRD_PD5(ALL1)
#define PWR_PDCRD_PD6(v) ( ( (v) & 0x1 ) << 6 )
#define PWR_PDCRD_PD6_MASK PWR_PDCRD_PD6(ALL1)
#define PWR_PDCRD_PD7(v) ( ( (v) & 0x1 ) << 7 )
#define PWR_PDCRD_PD7_MASK PWR_PDCRD_PD7(ALL1)
#define PWR_PDCRD_PD8(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_PDCRD_PD8_MASK PWR_PDCRD_PD8(ALL1)
#define PWR_PDCRD_PD9(v) ( ( (v) & 0x1 ) << 9 )
#define PWR_PDCRD_PD9_MASK PWR_PDCRD_PD9(ALL1)
#define PWR_PDCRD_PD10(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_PDCRD_PD10_MASK PWR_PDCRD_PD10(ALL1)
#define PWR_PDCRD_PD11(v) ( ( (v) & 0x1 ) << 11 )
#define PWR_PDCRD_PD11_MASK PWR_PDCRD_PD11(ALL1)
#define PWR_PDCRD_PD12(v) ( ( (v) & 0x1 ) << 12 )
#define PWR_PDCRD_PD12_MASK PWR_PDCRD_PD12(ALL1)
#define PWR_PDCRD_PD13(v) ( ( (v) & 0x1 ) << 13 )
#define PWR_PDCRD_PD13_MASK PWR_PDCRD_PD13(ALL1)
#define PWR_PDCRD_PD14(v) ( ( (v) & 0x1 ) << 14 )
#define PWR_PDCRD_PD14_MASK PWR_PDCRD_PD14(ALL1)
#define PWR_PDCRD_PD15(v) ( ( (v) & 0x1 ) << 15 )
#define PWR_PDCRD_PD15_MASK PWR_PDCRD_PD15(ALL1)

/* PWR PUCRE register macros */

#define PWR_PUCRE_PU0(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_PUCRE_PU0_MASK PWR_PUCRE_PU0(ALL1)
#define PWR_PUCRE_PU1(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_PUCRE_PU1_MASK PWR_PUCRE_PU1(ALL1)
#define PWR_PUCRE_PU2(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_PUCRE_PU2_MASK PWR_PUCRE_PU2(ALL1)
#define PWR_PUCRE_PU3(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_PUCRE_PU3_MASK PWR_PUCRE_PU3(ALL1)
#define PWR_PUCRE_PU4(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_PUCRE_PU4_MASK PWR_PUCRE_PU4(ALL1)
#define PWR_PUCRE_PU5(v) ( ( (v) & 0x1 ) << 5 )
#define PWR_PUCRE_PU5_MASK PWR_PUCRE_PU5(ALL1)
#define PWR_PUCRE_PU6(v) ( ( (v) & 0x1 ) << 6 )
#define PWR_PUCRE_PU6_MASK PWR_PUCRE_PU6(ALL1)
#define PWR_PUCRE_PU7(v) ( ( (v) & 0x1 ) << 7 )
#define PWR_PUCRE_PU7_MASK PWR_PUCRE_PU7(ALL1)
#define PWR_PUCRE_PU8(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_PUCRE_PU8_MASK PWR_PUCRE_PU8(ALL1)
#define PWR_PUCRE_PU9(v) ( ( (v) & 0x1 ) << 9 )
#define PWR_PUCRE_PU9_MASK PWR_PUCRE_PU9(ALL1)
#define PWR_PUCRE_PU10(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_PUCRE_PU10_MASK PWR_PUCRE_PU10(ALL1)
#define PWR_PUCRE_PU11(v) ( ( (v) & 0x1 ) << 11 )
#define PWR_PUCRE_PU11_MASK PWR_PUCRE_PU11(ALL1)
#define PWR_PUCRE_PU12(v) ( ( (v) & 0x1 ) << 12 )
#define PWR_PUCRE_PU12_MASK PWR_PUCRE_PU12(ALL1)
#define PWR_PUCRE_PU13(v) ( ( (v) & 0x1 ) << 13 )
#define PWR_PUCRE_PU13_MASK PWR_PUCRE_PU13(ALL1)
#define PWR_PUCRE_PU14(v) ( ( (v) & 0x1 ) << 14 )
#define PWR_PUCRE_PU14_MASK PWR_PUCRE_PU14(ALL1)
#define PWR_PUCRE_PU15(v) ( ( (v) & 0x1 ) << 15 )
#define PWR_PUCRE_PU15_MASK PWR_PUCRE_PU15(ALL1)

/* PWR PDCRE register macros */

#define PWR_PDCRE_PD0(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_PDCRE_PD0_MASK PWR_PDCRE_PD0(ALL1)
#define PWR_PDCRE_PD1(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_PDCRE_PD1_MASK PWR_PDCRE_PD1(ALL1)
#define PWR_PDCRE_PD2(v) ( ( (v) & 0x1 ) << 2 )
#define PWR_PDCRE_PD2_MASK PWR_PDCRE_PD2(ALL1)
#define PWR_PDCRE_PD3(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_PDCRE_PD3_MASK PWR_PDCRE_PD3(ALL1)
#define PWR_PDCRE_PD4(v) ( ( (v) & 0x1 ) << 4 )
#define PWR_PDCRE_PD4_MASK PWR_PDCRE_PD4(ALL1)
#define PWR_PDCRE_PD5(v) ( ( (v) & 0x1 ) << 5 )
#define PWR_PDCRE_PD5_MASK PWR_PDCRE_PD5(ALL1)
#define PWR_PDCRE_PD6(v) ( ( (v) & 0x1 ) << 6 )
#define PWR_PDCRE_PD6_MASK PWR_PDCRE_PD6(ALL1)
#define PWR_PDCRE_PD7(v) ( ( (v) & 0x1 ) << 7 )
#define PWR_PDCRE_PD7_MASK PWR_PDCRE_PD7(ALL1)
#define PWR_PDCRE_PD8(v) ( ( (v) & 0x1 ) << 8 )
#define PWR_PDCRE_PD8_MASK PWR_PDCRE_PD8(ALL1)
#define PWR_PDCRE_PD9(v) ( ( (v) & 0x1 ) << 9 )
#define PWR_PDCRE_PD9_MASK PWR_PDCRE_PD9(ALL1)
#define PWR_PDCRE_PD10(v) ( ( (v) & 0x1 ) << 10 )
#define PWR_PDCRE_PD10_MASK PWR_PDCRE_PD10(ALL1)
#define PWR_PDCRE_PD11(v) ( ( (v) & 0x1 ) << 11 )
#define PWR_PDCRE_PD11_MASK PWR_PDCRE_PD11(ALL1)
#define PWR_PDCRE_PD12(v) ( ( (v) & 0x1 ) << 12 )
#define PWR_PDCRE_PD12_MASK PWR_PDCRE_PD12(ALL1)
#define PWR_PDCRE_PD13(v) ( ( (v) & 0x1 ) << 13 )
#define PWR_PDCRE_PD13_MASK PWR_PDCRE_PD13(ALL1)
#define PWR_PDCRE_PD14(v) ( ( (v) & 0x1 ) << 14 )
#define PWR_PDCRE_PD14_MASK PWR_PDCRE_PD14(ALL1)
#define PWR_PDCRE_PD15(v) ( ( (v) & 0x1 ) << 15 )
#define PWR_PDCRE_PD15_MASK PWR_PDCRE_PD15(ALL1)

/* PWR PUCRH register macros */

#define PWR_PUCRH_PU0(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_PUCRH_PU0_MASK PWR_PUCRH_PU0(ALL1)
#define PWR_PUCRH_PU1(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_PUCRH_PU1_MASK PWR_PUCRH_PU1(ALL1)
#define PWR_PUCRH_PU3(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_PUCRH_PU3_MASK PWR_PUCRH_PU3(ALL1)

/* PWR PDCRH register macros */

#define PWR_PDCRH_PD0(v) ( ( (v) & 0x1 ) << 0 )
#define PWR_PDCRH_PD0_MASK PWR_PDCRH_PD0(ALL1)
#define PWR_PDCRH_PD1(v) ( ( (v) & 0x1 ) << 1 )
#define PWR_PDCRH_PD1_MASK PWR_PDCRH_PD1(ALL1)
#define PWR_PDCRH_PD3(v) ( ( (v) & 0x1 ) << 3 )
#define PWR_PDCRH_PD3_MASK PWR_PDCRH_PD3(ALL1)

#endif

