#ifndef STM32L432KC_RCC_H
#define STM32L432KC_RCC_H

#include <stdint.h>

#define ALL1 ( (uint32_t) 0xFFFFFFFF )

typedef struct {
	uint32_t CR;
	uint32_t ICSCR;
	uint32_t CFGR;
	uint32_t PLLCFGR;
	uint32_t PLLSAI1CFGR;
	uint32_t RESERVED0;
	uint32_t CIER;
	uint32_t CIFR;
	uint32_t CICR;
	uint32_t RESERVED1;
	uint32_t AHB1RSTR;
	uint32_t AHB2RSTR;
	uint32_t AHB3RSTR;
	uint32_t RESERVED2;
	uint32_t APB1RSTR1;
	uint32_t APB1RSTR2;
	uint32_t APB2RSTR;
	uint32_t RESERVED3;
	uint32_t AHB1ENR;
	uint32_t AHB2ENR;
	uint32_t AHB3ENR;
	uint32_t RESERVED4;
	uint32_t APB1ENR1;
	uint32_t APB1ENR2;
	uint32_t APB2ENR;
	uint32_t RESERVED5;
	uint32_t AHB1SMENR;
	uint32_t AHB2SMENR;
	uint32_t AHB3SMENR;
	uint32_t RESERVED6;
	uint32_t APB1SMENR1;
	uint32_t APB1SMENR2;
	uint32_t APB2SMENR;
	uint32_t RESERVED7;
	uint32_t CCIPR;
	uint32_t RESERVED8;
	uint32_t BDCR;
	uint32_t CSR;
	uint32_t CRRCR;
	uint32_t CCIPR2;
} RCC_REG_BLOCKS;

/* RCC registers as structs */

#define RCC ( (RCC_REG_BLOCKS volatile *) 0x40021000 )

/* RCC CR register macros */

#define RCC_CR_MSION(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_CR_MSION_MASK RCC_CR_MSION(ALL1)
#define RCC_CR_MSIRDY(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_CR_MSIRDY_MASK RCC_CR_MSIRDY(ALL1)
#define RCC_CR_MSIPLLEN(v) ( ( (v) & 0x1 ) << 2 )
#define RCC_CR_MSIPLLEN_MASK RCC_CR_MSIPLLEN(ALL1)
#define RCC_CR_MSIRGSEL(v) ( ( (v) & 0x1 ) << 3 )
#define RCC_CR_MSIRGSEL_MASK RCC_CR_MSIRGSEL(ALL1)
#define RCC_CR_MSIRANGE(v) ( ( (v) & 0xF ) << 4 )
#define RCC_CR_MSIRANGE_MASK RCC_CR_MSIRANGE(ALL1)
#define RCC_CR_HSION(v) ( ( (v) & 0x1 ) << 8 )
#define RCC_CR_HSION_MASK RCC_CR_HSION(ALL1)
#define RCC_CR_HSIKERON(v) ( ( (v) & 0x1 ) << 9 )
#define RCC_CR_HSIKERON_MASK RCC_CR_HSIKERON(ALL1)
#define RCC_CR_HSIRDY(v) ( ( (v) & 0x1 ) << 10 )
#define RCC_CR_HSIRDY_MASK RCC_CR_HSIRDY(ALL1)
#define RCC_CR_HSIASFS(v) ( ( (v) & 0x1 ) << 11 )
#define RCC_CR_HSIASFS_MASK RCC_CR_HASIASFS(ALL1)
#define RCC_CR_HSEON(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_CR_HSEON_MASK RCC_CR_HSEON(ALL1)
#define RCC_CR_HSERDY(v) ( ( (v) & 0x1 ) << 17 )
#define RCC_CR_HSERDY_MASK RCC_CR_HSERDY(ALL1)
#define RCC_CR_HSEBYP(v) ( ( (v) & 0x1 ) << 18 )
#define RCC_CR_HSEBYP_MASK RCC_CR_HSEBYP_MASK(ALL1)
#define RCC_CR_CSSON(v) ( ( (v) & 0x1 ) << 19 )
#define RCC_CR_CSSON_MASK RCC_CR_CSSON(ALL1)
#define RCC_CR_PLLON(v) ( ( (v) & 0x1 ) << 24 )
#define RCC_CR_PLLON_MASK RCC_CR_PLLON(ALL1)
#define RCC_CR_PLLRDY(v) ( ( (v) & 0x1 ) << 25 )
#define RCC_CR_PLLRDY_MASK RCC_CR_PLLON(ALL1)
#define RCC_CR_PLLSAI1ON(v) ( ( (v) & 0x1 ) << 26 )
#define RCC_CR_PLLSAI1ON_MASK RCC_CR_PLLSAI1ON(ALL1)
#define RCC_CR_PLLSAI1RDY(v) ( ( (v) & 0x1 ) << 27 )
#define RCC_CR_PLLSAI1RDY_MASK RCC_CR_PLLSAI1RDY(ALL1)

/* RCC ICSCR register macros */

#define RCC_ICSCR_MSICAL(v) ( ( (v) & 0xFF ) << 0 )
#define RCC_ICSCR_MSICAL_MASK RCC_ICSCR_MSICAL(ALL1)
#define RCC_ICSCR_MSITRIM(v) ( ( (v) & 0xFF ) << 8 )
#define RCC_ICSCR_MSITRIM_MASK RCC_ICSCR_MSITRIM(ALL1)
#define RCC_ICSCR_HSICAL(v) ( ( (v) & 0xFF ) << 16 )
#define RCC_ICSCR_HSICAL_MASK RCC_ICSCR_HISCAL(ALL1)
#define RCC_ICSCR_HSITRIM(v) ( ( (v) & 0xFF ) << 24 )
#define RCC_ICSCR_HSITRIM_MASK RCC_ICSCR_HSITRIM(ALL1)

/* RCC CFGR register macros */

#define RCC_CFGR_SW(v) ( ( (v) & 0x3 ) << 0 )
#define RCC_CFGR_SW_MASK RCC_CFGR_SW(ALL1)
#define RCC_CFGR_SWS(v) ( ( (v) & 0x3 ) << 2 )
#define RCC_CFGR_SWS_MASK RCC_CFGR_SWS(ALL1)
#define RCC_CFGR_HPRE(v) ( ( (v) & 0xF ) << 4 )
#define RCC_CFGR_HPRE_MASK RCC_CFGR_HPRE(ALL1)
#define RCC_CFGR_PPRE1(v) ( ( (v) & 0x7 ) << 8 )
#define RCC_CFGR_PPRE1_MASK RCC_CFGR_PPRE1(ALL1)
#define RCC_CFGR_PPRE2(v) ( ( (v) & 0x7 ) << 11 )
#define RCC_CFGR_PPRE2_MASK RCC_CFGR_PPRE2(ALL1)
#define RCC_CFGR_STOPWUCK(v) ( ( (v) & 0x1 ) << 15 )
#define RCC_CFGR_STOPWUCK_MASK RCC_CFGR_STOPWUCK(ALL1)
#define RCC_CFGR_MCOSEL(v) ( ( (v) & 0xF ) << 24 )
#define RCC_CFGR_MCOSEL_MASK RCC_CFGR_MCOSEL(ALL1)
#define RCC_CFGR_MCOPRE(v) ( ( (v) & 0x7 ) << 28 )
#define RCC_CFGR_MCOPRE_MASK RCC_CFGR_MCOPRE(ALL1)

/* RCC PLLCFGR register macros */

#define RCC_PLLCFGR_PLLSRC(v) ( ( (v) & 0x3 ) << 0 )
#define RCC_PLLCFGR_PLLSRC_MASK RCC_PLLCFGR_PLLSRC(ALL1)
#define RCC_PLLCFGR_PLLM(v) ( ( (v) & 0x7 ) << 4 )
#define RCC_PLLCFGR_PLLM_MASK RCC_PLLCFGR_PLLM(ALL1)
#define RCC_PLLCFGR_PLLN(v) ( ( (v) & 0x7F ) << 8 )
#define RCC_PLLCFGR_PLLN_MASK RCC_PLLCFGR_PLLN(ALL1)
#define RCC_PLLCFGR_PLLPEN(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_PLLCFGR_PLLPEN_MASK RCC_PLLCFGR_PLLPEN(ALL1)
#define RCC_PLLCFGR_PLLP(v) ( ( (v) & 0x1 ) << 17 )
#define RCC_PLLCFGR_PLLP_MASK RCC_PLLCFGR_PLLP(ALL1)
#define RCC_PLLCFGR_PLLQEN(v) ( ( (v) & 0x1 ) << 20 )
#define RCC_PLLCFGR_PLLQEN_MASK RCC_PLLCFGR_PLLQEN(ALL1)
#define RCC_PLLCFGR_PLLQ(v) ( ( (v) & 0x3 ) << 21 )
#define RCC_PLLCFGR_PLLQ_MASK RCC_PLLCFGR_PLLQ(ALL1)
#define RCC_PLLCFGR_PLLREN(v) ( ( (v) & 0x1 ) << 24 )
#define RCC_PLLCFGR_PLLREN_MASK RCC_PLLCFGR_PLLREN(ALL1)
#define RCC_PLLCFGR_PLLR(v) ( ( (v) & 0x3 ) << 25 )
#define RCC_PLLCFGR_PLLR_MASK RCC_PLLCFGR_PLLR(ALL1)
#define RCC_PLLCFGR_PLLPDIV(v) ( ( (v) & 0x1F ) << 27 )
#define RCC_PLLCFGR_PLLPDIV_MASK RCC_PLLCFGR_PLLPDIV(ALL1)

/* RCC PLLSAI1CFGR register macros */

#define RCC_PLLSAI1CFGR_PLLSAI1N(v) ( ( (v) & 0x7F ) << 8 )
#define RCC_PLLSAI1CFGR_PLLSAI1N_MASK RCC_PLLSAI1CFGR_PLLSAI1N(ALL1)
#define RCC_PLLSAI1CFGR_PLLSAI1PEN(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_PLLSAI1CFGR_PLLSAI1PEN_MASK RCC_PLLSAI1CFGR_PLLSAI1PEN(ALL1)
#define RCC_PLLSAI1CFGR_PLLSAI1P(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_PLLSAI1CFGR_PLLSAI1P_MASK RCC_PLLSAI1CFGR_PLLSAI1P(ALL1)
#define RCC_PLLSAI1CFGR_PLLSAI1QEN(v) ( ( (v) & 0x1 ) << 20 )
#define RCC_PLLSAI1CFGR_PLLSAI1QEN_MASK RCC_PLLSAI1CFGR_PLLSAI1QEN(ALL1)
#define RCC_PLLSAI1CFGR_PLLSAI1Q(v) ( ( (v) & 0x3 ) << 21 )
#define RCC_PLLSAI1CFGR_PLLSAI1Q_MASK RCC_PLLSAI1CFGR_PLLSAI1Q(ALL1)
#define RCC_PLLSAI1CFGR_PLLSAI1REN(v) ( ( (v) & 0x1 ) << 24 )
#define RCC_PLLSAI1CFGR_PLLSAI1REN_MASK RCC_PLLSAI1CFGR_PLLSAI1REN(ALL1)
#define RCC_PLLSAI1CFGR_PLLSAI1R(v) ( ( (v) & 0x3 ) << 25 )
#define RCC_PLLSAI1CFGR_PLLSAI1R_MASK RCC_PLLSAI1CFGR_PLLSAI1R(ALL1)
#define RCC_PLLSAI1CFGR_PLLSAI1PDIV(v) ( ( (v) & 0x1F ) << 27 )
#define RCC_PLLSAI1CFGR_PLLSAI1PDIV_MASK RCC_PLLSAI1CFGR_PLLSAI1PDIV(ALL1)

/* RCC CIER register macros */

#define RCC_CIER_LSIRDYIE(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_CIER_LSIRDYIE_MASK RCC_CIER_LSIRDYIE(ALL1)
#define RCC_CIER_LSERDYIE(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_CIER_LSERDYIE_MASK RCC_CIER_LSERDYIE(ALL1)
#define RCC_CIER_MSIRDYIE(v) ( ( (v) & 0x1 ) << 2 )
#define RCC_CIER_MSIRDYIE_MASK RCC_CIER_MSIRDYIE(ALL1)
#define RCC_CIER_HSIRDYIE(v) ( ( (v) & 0x1 ) << 3 )
#define RCC_CIER_HSIRDYIE_MASK RCC_CIER_HSIRDYIE(ALL1)
#define RCC_CIER_HSERDYIE(v) ( ( (v) & 0x1 ) << 4 )
#define RCC_CIER_HSERDYIE_MASK RCC_CIER_HSERDYIE(ALL1)
#define RCC_CIER_PLLRDYIE(v) ( ( (v) & 0x1 ) << 5 )
#define RCC_CIER_PLLRDYIE_MASK RCC_CIER_PLLRDYIE(ALL1)
#define RCC_CIER_PLLSAI1RDYIE(v) ( ( (v) & 0x1 ) << 6 )
#define RCC_CIER_PLLSAI1RDYIE_MASK RCC_CIER_PLLSAI1RDYIE(ALL1)
#define RCC_CIER_CSSLSE(v) ( ( (v) & 0x1 ) << 9 )
#define RCC_CIER_CSSLSE_MASK RCC_CIER_CSSLSE(ALL1)
#define RCC_CIER_CSSHSE(v) ( ( (v) & 0x1 ) << 10 )
#define RCC_CIER_CSSHSE_MASK RCC_CIER_CSSHSE(ALL1)

/* RCC CIFR register macros */

#define RCC_CIFR_LSIRDYF(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_CIFR_LSIRDYF_MASK RCC_CIFR_LSIRDYF(ALL1)
#define RCC_CIFR_LSERDYF(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_CIFR_LSERDYF_MASK RCC_CIFR_LSERDYF(ALL1)
#define RCC_CIFR_MSIRDYF(v) ( ( (v) & 0x1 ) << 2 )
#define RCC_CIFR_MSIRDYF_MASK RCC_CIFR_MSIRDYF(ALL1)
#define RCC_CIFR_HSIRDYF(v) ( ( (v) & 0x1 ) << 3 )
#define RCC_CIFR_HSIRDYF_MASK RCC_CIFR_HSIRDYF(ALL1)
#define RCC_CIFR_HSERDYF(v) ( ( (v) & 0x1 ) << 4 )
#define RCC_CIFR_HSERDYF_MASK RCC_CIFR_HSERDYF(ALL1)
#define RCC_CIFR_PLLRDYF(v) ( ( (v) & 0x1 ) << 5 )
#define RCC_CIFR_PLLRDYF_MASK RCC_CIFR_PLLRDYF(ALL1)
#define RCC_CIFR_PLLSAI1RDYF(v) ( ( (v) & 0x1 ) << 6 )
#define RCC_CIFR_PLLSAI1RDYF_MASK RCC_CIFR_PLLSAI1RDYF(ALL1)
#define RCC_CIFR_CSSLSEF(v) ( ( (v) & 0x1 ) << 9 )
#define RCC_CIFR_CSSLSEF_MASK RCC_CIFR_CSSLSEF(ALL1)
#define RCC_CIFR_CSSHSEF(v) ( ( (v) & 0x1 ) << 10 )
#define RCC_CIFR_CSSHSEF_MASK RCC_CIFR_CSSHSEF(ALL1)

/* RCC CICR register macros */

#define RCC_CICR_LSIRDYC(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_CICR_LSIRDYC_MASK RCC_CICR_LSIRDYC(ALL1)
#define RCC_CICR_LSERDYC(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_CICR_LSERDYC_MASK RCC_CICR_LSERDYC(ALL1)
#define RCC_CICR_MSIRDYC(v) ( ( (v) & 0x1 ) << 2 )
#define RCC_CICR_MSIRDYC_MASK RCC_CICR_MSIRDYC(ALL1)
#define RCC_CICR_HSIRDYC(v) ( ( (v) & 0x1 ) << 3 )
#define RCC_CICR_HSIRDYC_MASK RCC_CICR_HSIRDYC(ALL1)
#define RCC_CICR_HSERDYC(v) ( ( (v) & 0x1 ) << 4 )
#define RCC_CICR_HSERDYC_MASK RCC_CICR_HSERDYC(ALL1)
#define RCC_CICR_PLLRDYC(v) ( ( (v) & 0x1 ) << 5 )
#define RCC_CICR_PLLRDYC_MASK RCC_CICR_PLLRDYC(ALL1)
#define RCC_CICR_PLLSAI1RDYC(v) ( ( (v) & 0x1 ) << 6 )
#define RCC_CICR_PLLSAI1RDYC_MASK RCC_CICR_PLLSAI1RDYC(ALL1)
#define RCC_CICR_CSSLSEC(v) ( ( (v) & 0x1 ) << 9 )
#define RCC_CICR_CSSLSEC_MASK RCC_CICR_CSSLSEC(ALL1)
#define RCC_CICR_CSSHSEC(v) ( ( (v) & 0x1 ) << 10 )
#define RCC_CICR_CSSHSEC_MASK RCC_CICR_CSSHSEC(ALL1)

/* RCC AHB1RSTR register macros */

#define RCC_AHB1RSTR_DMA1RST(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_AHB1RSTR_DMA1RST_MASK RCC_AHB1RSTR_DMA1RST(ALL1)
#define RCC_AHB1RSTR_DMA2RST(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_AHB1RSTR_DMA2RST_MASK RCC_AHB1RSTR_DMA2RST(ALL1)
#define RCC_AHB1RSTR_FLASHRST(v) ( ( (v) & 0x1 ) << 6 )
#define RCC_AHB1RSTR_FLASHRST_MASK RCC_AHB1RSTR_FLASHRST(ALL1)
#define RCC_AHB1RSTR_CRCRST(v) ( ( (v) & 0x1 ) << 12 )
#define RCC_AHB1RSTR_CRCRST_MASK RCC_AHB1RSTR_CRCRST(ALL1)
#define RCC_AHB1RSTR_TSCRST(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_AHB1RSTR_TSCRST_MASK RCC_AHB1RSTR_TSCRST(ALL1)

/* RCC AHB2RSTR register macros */

#define RCC_AHB2RSTR_GPIOARST(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_AHB2RSTR_GPIOARST_MASK RCC_AHB2RSTR_GPIOARST(ALL1)
#define RCC_AHB2RSTR_GPIOBRST(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_AHB2RSTR_GPIOBRST_MASK RCC_AHB2RSTR_GPIOBRST(ALL1)
#define RCC_AHB2RSTR_GPIOCRST(v) ( ( (v) & 0x1 ) << 2 )
#define RCC_AHB2RSTR_GPIOCRST_MASK RCC_AHB2RSTR_GPIOCRST(ALL1)
#define RCC_AHB2RSTR_GPIOHRST(v) ( ( (v) & 0x1 ) << 7 )
#define RCC_AHB2RSTR_GPIOHRST_MASK RCC_AHB2RSTR_GPIOHRST(ALL1)
#define RCC_AHB2RSTR_ADCRST(v) ( ( (v) & 0x1 ) << 13 )
#define RCC_AHB2RSTR_ADCRST_MASK RCC_AHB2RSTR_ADCRST(ALL1)
#define RCC_AHB2RSTR_AESRST(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_AHB2RSTR_AESRST_MASK RCC_AHB2RSTR_AESRST(ALL1)
#define RCC_AHB2RSTR_RNGRST(v) ( ( (v) & 0x1 ) << 18 )
#define RCC_AHB2RSTR_RNGRST_MASK RCC_AHB2RSTR_RNGRST(ALL1)

/* RCC AHB3RSTR register macros */

#define RCC_AHB3RSTR_QSPIRST(v) ( ( (v) & 0x1 ) << 8 )
#define RCC_AHB3RSTR_QSPIRST_MASK RCC_AHB3RSTR_QSPIRST(ALL1)

/* RCC APB1RSTR1 register macros */

#define RCC_APB1RSTR1_TIM2RST(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_APB1RSTR1_TIM2RST_MASK RCC_APB1RSTR1_TIM2RST(ALL1)
#define RCC_APB1RSTR1_TIM3RST(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_APB1RSTR1_TIM3RST_MASK RCC_APB1RSTR1_TIM3RST(ALL1)
#define RCC_APB1RSTR1_TIM6RST(v) ( ( (v) & 0x1 ) << 4 )
#define RCC_APB1RSTR1_TIM6RST_MASK RCC_APB1RSTR1_TIM6RST(ALL1)
#define RCC_APB1RSTR1_TIM7RST(v) ( ( (v) & 0x1 ) << 5 )
#define RCC_APB1RSTR1_TIM7RST_MASK RCC_APB1RSTR1_TIM7RST(ALL1)
#define RCC_APB1RSTR1_SPI2RST(v) ( ( (v) & 0x1 ) << 14 )
#define RCC_APB1RSTR1_SPI2RST_MASK RCC_APB1RSTR1_SPI2RST(ALL1)
#define RCC_APB1RSTR1_SPI3RST(v) ( ( (v) & 0x1 ) << 15 )
#define RCC_APB1RSTR1_SPI3RST_MASK RCC_APB1RSTR1_SPI3RST(ALL1)
#define RCC_APB1RSTR1_USART2RST(v) ( ( (v) & 0x1 ) << 17 )
#define RCC_APB1RSTR1_USART2RST_MASK RCC_APB1RSTR1_USART2RST(ALL1)
#define RCC_APB1RSTR1_I2C1RST(v) ( ( (v) & 0x1 ) << 21 )
#define RCC_APB1RSTR1_I2C1RST_MASK RCC_APB1RSTR1_I2C1RST(ALL1)
#define RCC_APB1RSTR1_I2C3RST(v) ( ( (v) & 0x1 ) << 23 )
#define RCC_APB1RSTR1_I2C3RST_MASK RCC_APB1RSTR1_I2C3RST(ALL1)
#define RCC_APB1RSTR1_CRSRST(v) ( ( (v) & 0x1 ) << 24 )
#define RCC_APB1RSTR1_CRSRST_MASK RCC_APB1RSTR1_CRSRST(ALL1)
#define RCC_APB1RSTR1_CAN1RST(v) ( ( (v) & 0x1 ) << 25 )
#define RCC_APB1RSTR1_CAN1RST_MASK RCC_APB1RSTR1_CAN1RST(ALL1)
#define RCC_APB1RSTR1_USBFSRST(v) ( ( (v) & 0x1 ) << 26 )
#define RCC_APB1RSTR1_USBFSRST_MASK RCC_APB1RSTR1_USBFSRST(ALL1)
#define RCC_APB1RSTR1_PWRRST(v) ( ( (v) & 0x1 ) << 28 )
#define RCC_APB1RSTR1_PWRRST_MASK RCC_APB1RSTR1_PWRRST(ALL1)
#define RCC_APB1RSTR1_DAC1RST(v) ( ( (v) & 0x1 ) << 29 )
#define RCC_APB1RSTR1_DAC1RST_MASK RCC_APB1RSTR1_DAC1RST(ALL1)
#define RCC_APB1RSTR1_OPAMPRST(v) ( ( (v) & 0x1 ) << 30 )
#define RCC_APB1RSTR1_OPAMPRST_MASK RCC_APB1RSTR1_OPAMPRST(ALL1)
#define RCC_APB1RSTR1_LPTIM1RST(v) ( ( (v) & 0x1 ) << 31 )
#define RCC_APB1RSTR1_LPTIM1RST_MASK RCC_APB1RSTR1_LPTIM1RST(ALL1)

/* RCC APB1RSTR2 register macros */

#define RCC_APB1RSTR2_LPUART1RST(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_APB1RSTR2_LPUART1RST_MASK RCC_APB1RSTR2_LPUART1RST(ALL1)
#define RCC_APB1RSTR2_SWPMI1RST(v) ( ( (v) & 0x1 ) << 2 )
#define RCC_APB1RSTR2_SWPMI1RST_MASK RCC_APB1RSTR2_SWPMI1RST(ALL1)
#define RCC_APB1RSTR2_LPTIM2RST(v) ( ( (v) & 0x1 ) << 5 )
#define RCC_APB1RSTR2_LPTIM2RST_MASK RCC_APB1RSTR2_LPTIM2RST(ALL1)

/* RCC APB2RSTR register macros */

#define RCC_APB2RSTR_SYSCFGRST(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_APB2RSTR_SYSCFGRST_MASK RCC_APB2RSTR_SYSCFGRST(ALL1)
#define RCC_APB2RSTR_TIM1RST(v) ( ( (v) & 0x1 ) << 11 )
#define RCC_APB2RSTR_TIM1RST_MASK RCC_APB2RSTR_TIM1RST(ALL1)
#define RCC_APB2RSTR_SPI1RST(v) ( ( (v) & 0x1 ) << 12 )
#define RCC_APB2RSTR_SPI1RST_MASK RCC_APB2RSTR_SPI1RST(ALL1)
#define RCC_APB2RSTR_USART1RST(v) ( ( (v) & 0x1 ) << 14 )
#define RCC_APB2RSTR_USART1RST_MASK RCC_APB2RSTR_USART1RST(ALL1)
#define RCC_APB2RSTR_TIM15RST(v) ( ( (v) & 0x1 ) << 15 )
#define RCC_APB2RSTR_TIM15RST_MASK RCC_APB2RSTR_TIM15RST(ALL1)
#define RCC_APB2RSTR_TIM16RST(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_APB2RSTR_TIM16RST_MASK RCC_APB2RSTR_TIM16RST(ALL1)
#define RCC_APB2RSTR_SAI1RST(v) ( ( (v) & 0x1 ) << 21 )
#define RCC_APB2RSTR_SAI1RST_MASK RCC_APB2RSTR_SAI1RST(ALL1)
#define RCC_APB2RSTR_DFSDM1RST(v) ( ( (v) & 0x1 ) << 24 )
#define RCC_APB2RSTR_DFSDM1RST_MASK RCC_APB2RSTR_DFSDM1RST(ALL1)

/* RCC AHB1ENR register macros */

#define RCC_AHB1ENR_DMA1EN(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_AHB1ENR_DMA1EN_MASK RCC_AHB1ENR_DMA1EN(ALL1)
#define RCC_AHB1ENR_DMA2EN(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_AHB1ENR_DMA2EN_MASK RCC_AHB1ENR_DMA2EN(ALL1)
#define RCC_AHB1ENR_FLASHEN(v) ( ( (v) & 0x1 ) << 6 )
#define RCC_AHB1ENR_FLASHEN_MASK RCC_AHB1ENR_FLASHEN(ALL1)
#define RCC_AHB1ENR_CRCEN(v) ( ( (v) & 0x1 ) << 12 )
#define RCC_AHB1ENR_CRCEN_MASK RCC_AHB1ENR_CRCEN(ALL1)
#define RCC_AHB1ENR_TSCEN(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_AHB1ENR_TSCEN_MASK RCC_AHB1ENR_TSCEN(ALL1)

/* RCC AHB2ENR register macros */

#define RCC_AHB2ENR_GPIOAEN(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_AHB2ENR_GPIOAEN_MASK RCC_AHB2ENR_GPIOAEN(ALL1)
#define RCC_AHB2ENR_GPIOBEN(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_AHB2ENR_GPIOBEN_MASK RCC_AHB2ENR_GPIOBEN(ALL1)
#define RCC_AHB2ENR_GPIOCEN(v) ( ( (v) & 0x1 ) << 2 )
#define RCC_AHB2ENR_GPIOCEN_MASK RCC_AHB2ENR_GPIOCEN(ALL1)
#define RCC_AHB2ENR_GPIOHEN(v) ( ( (v) & 0x1 ) << 7 )
#define RCC_AHB2ENR_GPIOHEN_MASK RCC_AHB2ENR_GPIOHEN(ALL1)
#define RCC_AHB2ENR_ADCEN(v) ( ( (v) & 0x1 ) << 13 )
#define RCC_AHB2ENR_ADCEN_MASK RCC_AHB2ENR_ADCEN(ALL1)
#define RCC_AHB2ENR_AESEN(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_AHB2ENR_AESEN_MASK RCC_AHB2ENR_AESEN(ALL1)
#define RCC_AHB2ENR_RNGEN(v) ( ( (v) & 0x1 ) << 18 )
#define RCC_AHB2ENR_RNGEN_MASK RCC_AHB2ENR_RNGEN(ALL1)

/* RCC AHB3ENR register macros */

#define RCC_AHB3ENR_QSPIEN(v) ( ( (v) & 0x1 ) << 8 )
#define RCC_AHB3ENR_QSPIEN_MASK RCC_AHB3ENR_QSPIEN(ALL1)

/* RCC APB1ENR1 register macros */

#define RCC_APB1ENR1_TIM2EN(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_APB1ENR1_TIM2EN_MASK RCC_APB1ENR1_TIM2EN(ALL1)
#define RCC_APB1ENR1_TIM3EN(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_APB1ENR1_TIM3EN_MASK RCC_APB1ENR1_TIM3EN(ALL1)
#define RCC_APB1ENR1_TIM6EN(v) ( ( (v) & 0x1 ) << 4 )
#define RCC_APB1ENR1_TIM6EN_MASK RCC_APB1ENR1_TIM6EN(ALL1)
#define RCC_APB1ENR1_TIM7EN(v) ( ( (v) & 0x1 ) << 5 )
#define RCC_APB1ENR1_TIM7EN_MASK RCC_APB1ENR1_TIM7EN(ALL1)
#define RCC_APB1ENR1_RTCAPBEN(v) ( ( (v) & 0x1 ) << 10 )
#define RCC_APB1ENR1_RTCAPBEN_MASK RCC_APB1ENR1_RTCAPBEN(ALL1)
#define RCC_APB1ENR1_WWDGEN(v) ( ( (v) & 0x1 ) << 11 )
#define RCC_APB1ENR1_WWDGEN_MASK RCC_APB1ENR1_WWDGEN(ALL1)
#define RCC_APB1ENR1_SPI2EN(v) ( ( (v) & 0x1 ) << 14 )
#define RCC_APB1ENR1_SPI2EN_MASK RCC_APB1ENR1_SPI2EN(ALL1)
#define RCC_APB1ENR1_SPI3EN(v) ( ( (v) & 0x1 ) << 15 )
#define RCC_APB1ENR1_SPI3EN_MASK RCC_APB1ENR1_SPI3EN(ALL1)
#define RCC_APB1ENR1_USART2EN(v) ( ( (v) & 0x1 ) << 17 )
#define RCC_APB1ENR1_USART2EN_MASK RCC_APB1ENR1_USART2EN(ALL1)
#define RCC_APB1ENR1_I2C1EN(v) ( ( (v) & 0x1 ) << 21 )
#define RCC_APB1ENR1_I2C1EN_MASK RCC_APB1ENR1_I2C1EN(ALL1)
#define RCC_APB1ENR1_I2C3EN(v) ( ( (v) & 0x1 ) << 23 )
#define RCC_APB1ENR1_I2C3EN_MASK RCC_APB1ENR1_I2C3EN(ALL1)
#define RCC_APB1ENR1_CRSEN(v) ( ( (v) & 0x1 ) << 24 )
#define RCC_APB1ENR1_CRSEN_MASK RCC_APB1ENR1_CRSEN(ALL1)
#define RCC_APB1ENR1_CAN1EN(v) ( ( (v) & 0x1 ) << 25 )
#define RCC_APB1ENR1_CAN1EN_MASK RCC_APB1ENR1_CAN1EN(ALL1)
#define RCC_APB1ENR1_USBFSEN(v) ( ( (v) & 0x1 ) << 26 )
#define RCC_APB1ENR1_USBFSEN_MASK RCC_APB1ENR1_USBFSEN(ALL1)
#define RCC_APB1ENR1_PWREN(v) ( ( (v) & 0x1 ) << 28 )
#define RCC_APB1ENR1_PWREN_MASK RCC_APB1ENR1_PWREN(ALL1)
#define RCC_APB1ENR1_DAC1EN(v) ( ( (v) & 0x1 ) << 29 )
#define RCC_APB1ENR1_DAC1EN_MASK RCC_APB1ENR1_DAC1EN(ALL1)
#define RCC_APB1ENR1_OPAMPEN(v) ( ( (v) & 0x1 ) << 30 )
#define RCC_APB1ENR1_OPAMPEN_MASK RCC_APB1ENR1_OPAMPEN(ALL1)
#define RCC_APB1ENR1_LPTIM1EN(v) ( ( (v) & 0x1 ) << 31 )
#define RCC_APB1ENR1_LPTIM1EN_MASK RCC_APB1ENR1_LPTIM1EN(ALL1)

/* RCC APB1ENR2 register macros */

#define RCC_APB1ENR2_LPUART1EN(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_APB1ENR2_LPUART1EN_MASK RCC_APB1ENR2_LPUART1EN(ALL1)
#define RCC_APB1ENR2_SWPMI1EN(v) ( ( (v) & 0x1 ) << 2 )
#define RCC_APB1ENR2_SWPMI1EN_MASK RCC_APB1ENR2_SWPMI1EN(ALL1)
#define RCC_APB1ENR2_LPTIM2EN(v) ( ( (v) & 0x1 ) << 5 )
#define RCC_APB1ENR2_LPTIM2EN_MASK RCC_APB1ENR2_LPTIM2EN(ALL1)

/* RCC APB2ENR register macros */

#define RCC_APB2ENR_SYSCFGEN(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_APB2ENR_SYSCFGEN_MASK RCC_APB2ENR_SYSCFGEN(ALL1)
#define RCC_APB2ENR_FWEN(v) ( ( (v) & 0x1 ) << 7 )
#define RCC_APB2ENR_FWEN_MASK RCC_APB2ENR_FWEN(ALL1)
#define RCC_APB2ENR_TIMEN(v) ( ( (v) & 0x1 ) << 11 )
#define RCC_APB2ENR_TIMEN_MASK RCC_APB2ENR_TIMEN(ALL1)
#define RCC_APB2ENR_SPI1EN(v) ( ( (v) & 0x1 ) << 12 )
#define RCC_APB2ENR_SPI1EN_MASK RCC_APB2ENR_SPI1EN(ALL1)
#define RCC_APB2ENR_USART1EN(v) ( ( (v) & 0x1 ) << 14 )
#define RCC_APB2ENR_USART1EN_MASK RCC_APB2ENR_USART1EN(ALL1)
#define RCC_APB2ENR_TIM15EN(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_APB2ENR_TIM15EN_MASK RCC_APB2ENR_TIM15EN(ALL1)
#define RCC_APB2ENR_TIM16EN(v) ( ( (v) & 0x1 ) << 17 )
#define RCC_APB2ENR_TIM16EN_MASK RCC_APB2ENR_TIM16EN(ALL1)
#define RCC_APB2ENR_SAI2EN(v) ( ( (v) & 0x1 ) << 21 )
#define RCC_APB2ENR_SAI2EN_MASK RCC_APB2ENR_SAI2EN(ALL1)

/* RCC AHB1SMENR register macros */

#define RCC_AHB1SMENR_DMA1SMEN(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_AHB1SMENR_DMA1SMEN_MASK RCC_AHB1SMENR_DMA1SMEN(ALL1)
#define RCC_AHB1SMENR_DMA2SMEN(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_AHB1SMENR_DMA2SMEN_MASK RCC_AHB1SMENR_DMA2SMEN(ALL1)
#define RCC_AHB1SMENR_FLASHSMEN(v) ( ( (v) & 0x1 ) << 6 )
#define RCC_AHB1SMENR_FLASHSMEN_MASK RCC_AHB1SMENR_FLASHSMEN(ALL1)
#define RCC_AHB1SMENR_CRCSMEN(v) ( ( (v) & 0x1 ) << 12 )
#define RCC_AHB1SMENR_CRCSMEN_MASK RCC_AHB1SMENR_CRCSMEN(ALL1)
#define RCC_AHB1SMENR_TSCSMEN(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_AHB1SMENR_TSCSMEN_MASK RCC_AHB1SMENR_TSCSMEN(ALL1)

/* RCC AHB2SMENR register macros */

#define RCC_AHB2SMENR_GPIOASMEN(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_AHB2SMENR_GPIOASMEN_MASK RCC_AHB2SMENR_GPIOASMEN(ALL1)
#define RCC_AHB2SMENR_GPIOBSMEN(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_AHB2SMENR_GPIOBSMEN_MASK RCC_AHB2SMENR_GPIOBSMEN(ALL1)
#define RCC_AHB2SMENR_GPIOCSMEN(v) ( ( (v) & 0x1 ) << 2 )
#define RCC_AHB2SMENR_GPIOCSMEN_MASK RCC_AHB2SMENR_GPIOCSMEN(ALL1)
#define RCC_AHB2SMENR_GPIOHSMEN(v) ( ( (v) & 0x1 ) << 7 )
#define RCC_AHB2SMENR_GPIOHSMEN_MASK RCC_AHB2SMENR_GPIOHSMEN(ALL1)
#define RCC_AHB2SMENR_ADCSMEN(v) ( ( (v) & 0x1 ) << 13 )
#define RCC_AHB2SMENR_ADCSMEN_MASK RCC_AHB2SMENR_ADCSMEN(ALL1)
#define RCC_AHB2SMENR_AESSMEN(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_AHB2SMENR_AESSMEN_MASK RCC_AHB2SMENR_AESSMEN(ALL1)
#define RCC_AHB2SMENR_RNGSMEN(v) ( ( (v) & 0x1 ) << 18 )
#define RCC_AHB2SMENR_RNGSMEN_MASK RCC_AHB2SMENR_RNGSMEN(ALL1)

/* RCC AHB3SMENR register macros */

#define RCC_AHB3SMENR_QSPISMEN(v) ( ( (v) & 0x1 ) << 8 )
#define RCC_AHB3SMENR_QSPISMEN_MASK RCC_AHB3SMENR_QSPISMEN(ALL1)

/* RCC APB1SMENR1 register macros */

#define RCC_APB1SMENR1_TIM2SMEN(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_APB1SMENR1_TIM2SMEN_MASK RCC_APB1SMENR1_TIM2SMEN(ALL1)
#define RCC_APB1SMENR1_TIM3SMEN(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_APB1SMENR1_TIM3SMEN_MASK RCC_APB1SMENR1_TIM3SMEN(ALL1)
#define RCC_APB1SMENR1_TIM6SMEN(v) ( ( (v) & 0x1 ) << 4 )
#define RCC_APB1SMENR1_TIM6SMEN_MASK RCC_APB1SMENR1_TIM6SMEN(ALL1)
#define RCC_APB1SMENR1_TIM7SMEN(v) ( ( (v) & 0x1 ) << 5 )
#define RCC_APB1SMENR1_TIM7SMEN_MASK RCC_APB1SMENR1_TIM7SMEN(ALL1)
#define RCC_APB1SMENR1_RTCAPBSMEN(v) ( ( (v) & 0x1 ) << 10 )
#define RCC_APB1SMENR1_RTCAPBSMEN_MASK RCC_APB1SMENR1_RTCAPBSMEN(ALL1)
#define RCC_APB1SMENR1_WWDGSMEN(v) ( ( (v) & 0x1 ) << 11 )
#define RCC_APB1SMENR1_WWDGSMEN_MASK RCC_APB1SMENR1_WWDGSMEN(ALL1)
#define RCC_APB1SMENR1_SPI2SMEN(v) ( ( (v) & 0x1 ) << 14 )
#define RCC_APB1SMENR1_SPI2SMEN_MASK RCC_APB1SMENR1_SPI2SMEN(ALL1)
#define RCC_APB1SMENR1_SPI3SMEN(v) ( ( (v) & 0x1 ) << 15 )
#define RCC_APB1SMENR1_SPI3SMEN_MASK RCC_APB1SMENR1_SPI3SMEN(ALL1)
#define RCC_APB1SMENR1_USART2SMEN(v) ( ( (v) & 0x1 ) << 17 )
#define RCC_APB1SMENR1_USART2SMEN_MASK RCC_APB1SMENR1_USART2SMEN(ALL1)
#define RCC_APB1SMENR1_I2C1SMEN(v) ( ( (v) & 0x1 ) << 21 )
#define RCC_APB1SMENR1_I2C1SMEN_MASK RCC_APB1SMENR1_I2C1SMEN(ALL1)
#define RCC_APB1SMENR1_I2C3SMEN(v) ( ( (v) & 0x1 ) << 23 )
#define RCC_APB1SMENR1_I2C3SMEN_MASK RCC_APB1SMENR1_I2C3SMEN(ALL1)
#define RCC_APB1SMENR1_CRSSMEN(v) ( ( (v) & 0x1 ) << 24 )
#define RCC_APB1SMENR1_CRSSMEN_MASK RCC_APB1SMENR1_CRSSMEN(ALL1)
#define RCC_APB1SMENR1_CAN1SMEN(v) ( ( (v) & 0x1 ) << 25 )
#define RCC_APB1SMENR1_CAN1SMEN_MASK RCC_APB1SMENR1_CAN1SMEN(ALL1)
#define RCC_APB1SMENR1_USBFSSMEN(v) ( ( (v) & 0x1 ) << 26 )
#define RCC_APB1SMENR1_USBFSSMEN_MASK RCC_APB1SMENR1_USBFSSMEN(ALL1)
#define RCC_APB1SMENR1_PWRSMEN(v) ( ( (v) & 0x1 ) << 28 )
#define RCC_APB1SMENR1_PWRSMEN_MASK RCC_APB1SMENR1_PWRSMEN(ALL1)
#define RCC_APB1SMENR1_DAC1SMEN(v) ( ( (v) & 0x1 ) << 29 )
#define RCC_APB1SMENR1_DAC1SMEN_MASK RCC_APB1SMENR1_DAC1SMEN(ALL1)
#define RCC_APB1SMENR1_OPAMPSMEN(v) ( ( (v) & 0x1 ) << 30 )
#define RCC_APB1SMENR1_OPAMPSMEN_MASK RCC_APB1SMENR1_OPAMPSMEN(ALL1)
#define RCC_APB1SMENR1_LPTIM1SMEN(v) ( ( (v) & 0x1 ) << 31 )
#define RCC_APB1SMENR1_LPTIM1SMEN_MASK RCC_APB1SMENR1_LPTIM1SMEN(ALL1)

/* RCC APB1SMENR2 register macros */

#define RCC_APB1SMENR2_LPUART1SMEN(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_APB1SMENR2_LPUART1SMEN_MASK RCC_APB1SMENR2_LPUART1SMEN(ALL1)
#define RCC_APB1SMENR2_SWPMI1SMEN(v) ( ( (v) & 0x1 ) << 2 )
#define RCC_APB1SMENR2_SWPMI1SMEN_MASK RCC_APB1SMENR2_SWPMI1SMEN(ALL1)
#define RCC_APB1SMENR2_LPTIM2SMEN(v) ( ( (v) & 0x1 ) << 5 )
#define RCC_APB1SMENR2_LPTIM2SMEN_MASK RCC_APB1SMENR2_LPTIM2SMEN(ALL1)

/* RCC APB2SMENR register macros */

#define RCC_APB2SMENR_SYSCFGSMENT(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_APB2SMENR_SYSCFGSMENT_MASK RCC_APB2SMENR_SYSCFGSMENT(ALL1)
#define RCC_APB2SMENR_FWSMEN(v) ( ( (v) & 0x1 ) << 7 )
#define RCC_APB2SMENR_FWSMEN_MASK RCC_APB2SMENR_FWSMEN(ALL1)
#define RCC_APB2SMENR_TIMSMEN(v) ( ( (v) & 0x1 ) << 11 )
#define RCC_APB2SMENR_TIMSMEN_MASK RCC_APB2SMENR_TIMSMEN(ALL1)
#define RCC_APB2SMENR_SPI1SMEN(v) ( ( (v) & 0x1 ) << 12 )
#define RCC_APB2SMENR_SPI1SMEN_MASK RCC_APB2SMENR_SPI1SMEN(ALL1)
#define RCC_APB2SMENR_USART1SMEN(v) ( ( (v) & 0x1 ) << 14 )
#define RCC_APB2SMENR_USART1SMEN_MASK RCC_APB2SMENR_USART1SMEN(ALL1)
#define RCC_APB2SMENR_TIM15SMEN(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_APB2SMENR_TIM15SMEN_MASK RCC_APB2SMENR_TIM15SMEN(ALL1)
#define RCC_APB2SMENR_TIM16SMEN(v) ( ( (v) & 0x1 ) << 17 )
#define RCC_APB2SMENR_TIM16SMEN_MASK RCC_APB2SMENR_TIM16SMEN(ALL1)
#define RCC_APB2SMENR_SAI2SMEN(v) ( ( (v) & 0x1 ) << 21 )
#define RCC_APB2SMENR_SAI2SMEN_MASK RCC_APB2SMENR_SAI2SMEN(ALL1)

/* RCC CCIPR register macros */

#define RCC_CCIPR_USART1SEL(v) ( ( (v) & 0x3 ) << 0 )
#define RCC_CCIPR_USART1SEL_MASK RCC_CCIPR_USART1SEL(ALL1)
#define RCC_CCIPR_USART2SEL(v) ( ( (v) & 0x3 ) << 2 )
#define RCC_CCIPR_USART2SEL_MASK RCC_CCIPR_USART2SEL(ALL1)
#define RCC_CCIPR_LPUART1SEL(v) ( ( (v) & 0x3 ) << 10 )
#define RCC_CCIPR_LPUART1SEL_MASK RCC_CCIPR_LPUART1SEL(ALL)
#define RCC_CCIPR_I2C1SEL(v) ( ( (v) & 0x3 ) << 12 )
#define RCC_CCIPR_I2C1SEL_MASK RCC_CCIPR_I2C1SEL(ALL1)
#define RCC_CCIPR_I2C3SEL(v) ( ( (v) & 0x3 ) << 16 )
#define RCC_CCIPR_I2C3SEL_MASK RCC_CCIPR_I2C3SEL(ALL1)
#define RCC_CCIPR_LPTIM1SEL(v) ( ( (v) & 0x3 ) << 18 )
#define RCC_CCIPR_LPTIM1SEL_MASK RCC_CCIPR_LPTIM1SEL(ALL1)
#define RCC_CCIPR_LPTIM2SEL(v) ( ( (v) & 0x3 ) << 20 )
#define RCC_CCIPR_LPTIM2SEL_MASK RCC_CCIPR_LPTIM2SEL(ALL1)
#define RCC_CCIPR_SAI1SEL(v) ( ( (v) & 0x3 ) << 22 )
#define RCC_CCIPR_SAI1SEL_MASK RCC_CCIPR_SAI1SEL(ALL1)
#define RCC_CCIPR_CLK48SEL(v) ( ( (v) & 0x3 ) << 26 )
#define RCC_CCIPR_CLK48SEL_MASK RCC_CCIPR_CLK48SEL(ALL1)
#define RCC_CCIPR_ADCSEL(v) ( ( (v) & 0x3 ) << 28 )
#define RCC_CCIPR_ADCSEL_MASK RCC_CCIPR_ADCSEL(ALL1)
#define RCC_CCIPR_SWPMI1SEL(v) ( ( (v) & 0x1 ) << 30 )
#define RCC_CCIPR_SWPMI1SEL_MASK RCC_CCIPR_SWPMI1SEL(ALL1)

/* RCC BDCR register macros */

#define RCC_BDCR_LSEON(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_BDCR_LSEON_MASK RCC_BDCR_LSEON(ALL1)
#define RCC_BDCR_LSERDY(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_BDCR_LSERDY_MASK RCC_BDCR_LSERDY(ALL1)
#define RCC_BDCR_LSEBYP(v) ( ( (v) & 0x1 ) << 2 )
#define RCC_BDCR_LSEBYP_MASK RCC_BDCR_LSEBYP(ALL1)
#define RCC_BDCR_LSEDRV(v) ( ( (v) & 0x3 ) << 3 )
#define RCC_BDCR_LSEDRV_MASK RCC_BDCR_LSEDRV(ALL1)
#define RCC_BDCR_LSECSSON(v) ( ( (v) & 0x5 ) << 5 )
#define RCC_BDCR_LSECSSON_MASK RCC_BDCR_LSECSSON(ALL1)
#define RCC_BDCR_LSECSSD(v) ( ( (v) & 0x1 ) << 6 )
#define RCC_BDCR_LSECSSD_MASK RCC_BDCR_LSECSSD(ALL1)
#define RCC_BDCR_RTCSEL(v) ( ( (v) & 0x3 ) << 8 )
#define RCC_BDCR_RTCSEL_MASK RCC_BDCR_RTCSEL(ALL1)
#define RCC_BDCR_RTCEN(v) ( ( (v) & 0x1 ) << 15 )
#define RCC_BDCR_RTCEN_MASK RCC_BDCR_RTCEN(ALL1)
#define RCC_BDCR_BDRST(v) ( ( (v) & 0x1 ) << 16 )
#define RCC_BDCR_BDRST_MASK RCC_BDCR_BDRST(ALL1)
#define RCC_BDCR_LSCOEN(v) ( ( (v) & 0x1 ) << 24 )
#define RCC_BDCR_LSCOEN_MASK RCC_BDCR_LSCOEN(ALL1)
#define RCC_BDCR_LSCOSEL(v) ( ( (v) & 0x1 ) << 25 )
#define RCC_BDCR_LSCOSEL_MASK RCC_BDCR_LSCOSEL(ALL1)

/* RCC CSR register macros */

#define RCC_CSR_LSION(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_CSR_LSION_MASK RCC_CSR_LSION(ALL1)
#define RCC_CSR_LSIRDY(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_CSR_LSIRDY_MASK RCC_CSR_LSION(ALL1)
#define RCC_CSR_MSISRANGE(v) ( ( (v) & 0xF ) << 8 )
#define RCC_CSR_MSISRANGE_MASK RCC_CSR_MSISRANGE(ALL1)
#define RCC_CSR_RMVF(v) ( ( (v) & 0x1 ) << 23 )
#define RCC_CSR_RMVF_MASK RCC_CSR_RMVF(ALL1)
#define RCC_CSR_FWRSTF(v) ( ( (v) & 0x1 ) << 24 )
#define RCC_CSR_FWRSTF_MASK RCC_CSR_FWRSTF(ALL1)
#define RCC_CSR_OBLRSTF(v) ( ( (v) & 0x1 ) << 25 )
#define RCC_CSR_OBLRSTF_MASK RCC_CSR_OBLRSTF(ALL1)
#define RCC_CSR_PINRSTF(v) ( ( (v) & 0x1 ) << 26 )
#define RCC_CSR_PINRSTF_MASK RCC_CSR_PINRSTF(ALL1)
#define RCC_CSR_BORRSTF(v) ( ( (v) & 0x1 ) << 27 )
#define RCC_CSR_BORRSTF_MASK RCC_CSR_BORRSTF(ALL1)
#define RCC_CSR_SFTRSTF(v) ( ( (v) & 0x1 ) << 28 )
#define RCC_CSR_SFTRSTF_MASK RCC_CSR_SFTRSTF(ALL1)
#define RCC_CSR_IWWGRSTF(v) ( ( (v) & 0x1 ) << 29 )
#define RCC_CSR_IWWGRSTF_MASK RCC_CSR_IWWGRSTF(ALL1)
#define RCC_CSR_WWDGRSTF(v) ( ( (v) & 0x1 ) << 30 )
#define RCC_CSR_WWDGRSTF_MASK RCC_CSR_WWDGRSTF(ALL1)
#define RCC_CSR_LPWRRSTF(v) ( ( (v) & 0x1 ) << 31 )
#define RCC_CSR_LPWRRSTF_MASK RCC_CSR_LPWRRSTF(ALL1)

/* RCC CRRCR register macros */

#define RCC_CRRCR_HSI48ON(v) ( ( (v) & 0x1 ) << 0 )
#define RCC_CRRCR_HSI48ON_MASK RCC_CRRCR_HSI48ON(ALL1)
#define RCC_CRRCR_HSI48RDY(v) ( ( (v) & 0x1 ) << 1 )
#define RCC_CRRCR_HSI48RDY_MASK RCC_CRRCR_HSI48RDY(ALL1)
#define RCC_CRRCR_HSI48CAL(v) ( ( (v) & 0x1FF ) << 7 )
#define RCC_CRRCR_HSI48CAL_MASK RCC_CRRCR_HSI48CAL(ALL1)

/* RCC CCIPR2 register marcos */

#define RCC_CCIPR2_I2C4SEL(v) ( ( (v) & 0x3 ) << 0 )
#define RCC_CCIPR2_I2C4SEL_MASK RCC_CCIPR2_I2C4SEL(ALL1)

#endif

