#ifndef STM32L432KC_SYSCFG_H
#define STM32L432KC_SYSCFG_H

#include <stdint.h>

#define ALL1 ( (uint32_t) 0xFFFFFFFF )

typedef struct {
    uint32_t MEMRMP;
    uint32_t CFGR1;
    uint32_t EXTICR1;
    uint32_t EXTICR2;
    uint32_t EXTICR3;
    uint32_t EXTICR4;
    uint32_t SCSR;
    uint32_t CFGR2;
    uint32_t SWPR;
    uint32_t SKR;
} SYSCFG_REG_BLOCKS;

/* SYSCFG registers as structs */

#define SYSCFG ( (SYSCFG_REG_BLOCKS volatile *) 0x40010000 )

/* SYSCFG MEMRMP register as macros */

#define SYSCFG_MEMRMP_MEM_MODE(v) ( ( (v) & 0x7 ) << 0 )
#define SYSCFG_MEMRMP_MEM_MODE_MASK SYSCFG_MEMRMP_MEM_MODE(ALL1)

/* SYSCFG CFGR1 register as macros */

#define SYSCFG_CFGR1_FWDIS(v) ( ( (v) & 0x1 ) << 0 )
#define SYSCFG_CFGR1_FWDIS_MASK SYSCFG_CFGR1_FWDIS(ALL1)
#define SYSCFG_CFGR1_BOOSTEN(v) ( ( (v) & 0x1 ) << 8 )
#define SYSCFG_CFGR1_BOOSTEN_MASK SYSCFG_CFGR1_BOOSTEN(ALL1)
#define SYSCFG_CFGR1_I2C_PB6_FMP(v) ( ( (v) & 0x1 ) << 16 )
#define SYSCFG_CFGR1_I2C_PB6_FMP_MASK SYSCFG_CFGR1_I2C_PB6_FMP(ALL1)
#define SYSCFG_CFGR1_I2C_PB7_FMP(v) ( ( (v) & 0x1 ) << 17 )
#define SYSCFG_CFGR1_I2C_PB7_FMP_MASK SYSCFG_CFGR1_I2C_PB7_FMP(ALL1)
#define SYSCFG_CFGR1_I2C_PB8_FMP(v) ( ( (v) & 0x1 ) << 18 )
#define SYSCFG_CFGR1_I2C_PB8_FMP_MASK SYSCFG_CFGR1_I2C_PB8_FMP(ALL1)
#define SYSCFG_CFGR1_I2C_PB9_FMP(v) ( ( (v) & 0x1 ) << 19 )
#define SYSCFG_CFGR1_I2C_PB9_FMP_MASK SYSCFG_CFGR1_I2C_PB9_FMP(ALL1)
#define SYSCFG_CFGR1_I2C1_FMP(v) ( ( (v) & 0x1 ) << 20 )
#define SYSCFG_CFGR1_I2C1_FMP_MASK SYSCFG_CFGR1_I2C1_FMP(ALL1)
#define SYSCFG_CFGR1_I2C2_FMP(v) ( ( (v) & 0x1 ) << 21 )
#define SYSCFG_CFGR1_I2C2_FMP_MASK SYSCFG_CFGR1_I2C2_FMP(ALL1)
#define SYSCFG_CFGR1_I2C3_FMP(v) ( ( (v) & 0x1 ) << 22 )
#define SYSCFG_CFGR1_I2C3_FMP_MASK SYSCFG_CFGR1_I2C3_FMP(ALL1)
#define SYSCFG_CFGR1_I2C4_FMP(v) ( ( (v) & 0x1 ) << 23 )
#define SYSCFG_CFGR1_I2C4_FMP_MASK SYSCFG_CFGR1_I2C4_FMP(ALL1)
#define SYSCFG_CFGR1_FPU_IE(v) ( ( (v) & 0x3F ) << 26 )
#define SYSCFG_CFGR1_FPU_IE_MASK SYSCFG_CFGR1_FPU_IE(ALL1)

/* SYSCFG EXTICR1 register as macros */

#define SYSCFG_EXTICR1_EXTI0(v) ( ( (v) & 0x7 ) << 0 )
#define SYSCFG_EXTICR1_EXTI0_MASK SYSCFG_EXTICR1_EXTI0(ALL1)
#define SYSCFG_EXTICR1_EXTI1(v) ( ( (v) & 0x7 ) << 4 )
#define SYSCFG_EXTICR1_EXTI1_MASK SYSCFG_EXTICR1_EXTI1(ALL1)
#define SYSCFG_EXTICR1_EXTI2(v) ( ( (v) & 0x7 ) << 8 )
#define SYSCFG_EXTICR1_EXTI2_MASK SYSCFG_EXTICR1_EXTI2(ALL1)
#define SYSCFG_EXTICR1_EXTI3(v) ( ( (v) & 0x7 ) << 12 )
#define SYSCFG_EXTICR1_EXTI3_MASK SYSCFG_EXTICR1_EXTI3(ALL1)

/* SYSCFG EXTICR2 register as macros */

#define SYSCFG_EXTICR1_EXTI4(v) ( ( (v) & 0x7 ) << 0 )
#define SYSCFG_EXTICR1_EXTI4_MASK SYSCFG_EXTICR1_EXTI4(ALL1)
#define SYSCFG_EXTICR1_EXTI5(v) ( ( (v) & 0x7 ) << 4 )
#define SYSCFG_EXTICR1_EXTI5_MASK SYSCFG_EXTICR1_EXTI5(ALL1)
#define SYSCFG_EXTICR1_EXTI6(v) ( ( (v) & 0x7 ) << 8 )
#define SYSCFG_EXTICR1_EXTI6_MASK SYSCFG_EXTICR1_EXTI6(ALL1)
#define SYSCFG_EXTICR1_EXTI7(v) ( ( (v) & 0x7 ) << 12 )
#define SYSCFG_EXTICR1_EXTI7_MASK SYSCFG_EXTICR1_EXTI7(ALL1)

/* SYSCFG EXTICR3 register as macros */

#define SYSCFG_EXTICR1_EXTI8(v) ( ( (v) & 0x7 ) << 0 )
#define SYSCFG_EXTICR1_EXTI8_MASK SYSCFG_EXTICR1_EXTI8(ALL1)
#define SYSCFG_EXTICR1_EXTI9(v) ( ( (v) & 0x7 ) << 4 )
#define SYSCFG_EXTICR1_EXTI9_MASK SYSCFG_EXTICR1_EXTI9(ALL1)
#define SYSCFG_EXTICR1_EXTI10(v) ( ( (v) & 0x7 ) << 8 )
#define SYSCFG_EXTICR1_EXTI10_MASK SYSCFG_EXTICR1_EXTI10(ALL1)
#define SYSCFG_EXTICR1_EXTI11(v) ( ( (v) & 0x7 ) << 12 )
#define SYSCFG_EXTICR1_EXTI11_MASK SYSCFG_EXTICR1_EXTI11(ALL1)

/* SYSCFG EXTICR4 register as macros */

#define SYSCFG_EXTICR1_EXTI12(v) ( ( (v) & 0x7 ) << 0 )
#define SYSCFG_EXTICR1_EXTI12_MASK SYSCFG_EXTICR1_EXTI12(ALL1)
#define SYSCFG_EXTICR1_EXTI13(v) ( ( (v) & 0x7 ) << 4 )
#define SYSCFG_EXTICR1_EXTI13_MASK SYSCFG_EXTICR1_EXTI13(ALL1)
#define SYSCFG_EXTICR1_EXTI14(v) ( ( (v) & 0x7 ) << 8 )
#define SYSCFG_EXTICR1_EXTI14_MASK SYSCFG_EXTICR1_EXTI14(ALL1)
#define SYSCFG_EXTICR1_EXTI15(v) ( ( (v) & 0x7 ) << 12 )
#define SYSCFG_EXTICR1_EXTI15_MASK SYSCFG_EXTICR1_EXTI15(ALL1)

/* SYSCFG SCSR register as macros */

#define SYSCFG_SCSR_SRAM2ER(v) ( ( (v) & 0x1 ) << 0 )
#define SYSCFG_SCSR_SRAM2ER_MASK SYSCFG_SCSR_SRAM2ER(ALL1)
#define SYSCFG_SCSR_SRAM2BSY(v) ( ( (v) & 0x1 ) << 1 )
#define SYSCFG_SCSR_SRAM2BSY_MASK SYSCFG_SCSR_SRAM2BSY(ALL1)

/* SYSCFG CFGR2 register as macros */

#define SYSCFG_CFGR2_CLL(v) ( ( (v) & 0x1 ) << 0 )
#define SYSCFG_CFGR2_CLL_MASK SYSCFG_CFGR2_CLL(ALL1)
#define SYSCFG_CFGR2_SPL(v) ( ( (v) & 0x1 ) << 1 )
#define SYSCFG_CFGR2_SPL_MASK SYSCFG_CFGR2_SPL(ALL1)
#define SYSCFG_CFGR2_PVDL(v) ( ( (v) & 0x1 ) << 2 )
#define SYSCFG_CFGR2_PVDL_MASK SYSCFG_CFGR2_PVDL(ALL1)
#define SYSCFG_CFGR2_ECCL(v) ( ( (v) & 0x1 ) << 3 )
#define SYSCFG_CFGR2_ECCL_MASK SYSCFG_CFGR2_ECCL(ALL1)
#define SYSCFG_CFGR2_SPF(v) ( ( (v) & 0x1 ) << 8 )
#define SYSCFG_CFGR2_SPF_MASK SYSCFG_CFGR2_SPF(ALL1)

/* SYSCFG SWPR register as macros */

#define SYSCFG_SWPR_P0WP(v) ( ( (v) & 0x1 ) << 0 )
#define SYSCFG_SWPR_P0WP_MASK SYSCFG_SWPR_P0WP(ALL1)
#define SYSCFG_SWPR_P1WP(v) ( ( (v) & 0x1 ) << 1 )
#define SYSCFG_SWPR_P1WP_MASK SYSCFG_SWPR_P1WP(ALL1)
#define SYSCFG_SWPR_P2WP(v) ( ( (v) & 0x1 ) << 2 )
#define SYSCFG_SWPR_P2WP_MASK SYSCFG_SWPR_P2WP(ALL1)
#define SYSCFG_SWPR_P3WP(v) ( ( (v) & 0x1 ) << 3 )
#define SYSCFG_SWPR_P3WP_MASK SYSCFG_SWPR_P3WP(ALL1)
#define SYSCFG_SWPR_P4WP(v) ( ( (v) & 0x1 ) << 4 )
#define SYSCFG_SWPR_P4WP_MASK SYSCFG_SWPR_P4WP(ALL1)
#define SYSCFG_SWPR_P5WP(v) ( ( (v) & 0x1 ) << 5 )
#define SYSCFG_SWPR_P5WP_MASK SYSCFG_SWPR_P5WP(ALL1)
#define SYSCFG_SWPR_P6WP(v) ( ( (v) & 0x1 ) << 6 )
#define SYSCFG_SWPR_P6WP_MASK SYSCFG_SWPR_P6WP(ALL1)
#define SYSCFG_SWPR_P7WP(v) ( ( (v) & 0x1 ) << 7 )
#define SYSCFG_SWPR_P7WP_MASK SYSCFG_SWPR_P7WP(ALL1)
#define SYSCFG_SWPR_P8WP(v) ( ( (v) & 0x1 ) << 8 )
#define SYSCFG_SWPR_P8WP_MASK SYSCFG_SWPR_P8WP(ALL1)
#define SYSCFG_SWPR_P9WP(v) ( ( (v) & 0x1 ) << 9 )
#define SYSCFG_SWPR_P9WP_MASK SYSCFG_SWPR_P9WP(ALL1)
#define SYSCFG_SWPR_P10WP(v) ( ( (v) & 0x1 ) << 10 )
#define SYSCFG_SWPR_P10WP_MASK SYSCFG_SWPR_P10WP(ALL1)
#define SYSCFG_SWPR_P11WP(v) ( ( (v) & 0x1 ) << 11 )
#define SYSCFG_SWPR_P11WP_MASK SYSCFG_SWPR_P11WP(ALL1)
#define SYSCFG_SWPR_P12WP(v) ( ( (v) & 0x1 ) << 12 )
#define SYSCFG_SWPR_P12WP_MASK SYSCFG_SWPR_P12WP(ALL1)
#define SYSCFG_SWPR_P13WP(v) ( ( (v) & 0x1 ) << 13 )
#define SYSCFG_SWPR_P13WP_MASK SYSCFG_SWPR_P13WP(ALL1)
#define SYSCFG_SWPR_P14WP(v) ( ( (v) & 0x1 ) << 14 )
#define SYSCFG_SWPR_P14WP_MASK SYSCFG_SWPR_P14WP(ALL1)
#define SYSCFG_SWPR_P15WP(v) ( ( (v) & 0x1 ) << 15 )
#define SYSCFG_SWPR_P15WP_MASK SYSCFG_SWPR_P15WP(ALL1)
#define SYSCFG_SWPR_P16WP(v) ( ( (v) & 0x1 ) << 16 )
#define SYSCFG_SWPR_P16WP_MASK SYSCFG_SWPR_P16WP(ALL1)
#define SYSCFG_SWPR_P17WP(v) ( ( (v) & 0x1 ) << 17 )
#define SYSCFG_SWPR_P17WP_MASK SYSCFG_SWPR_P17WP(ALL1)
#define SYSCFG_SWPR_P18WP(v) ( ( (v) & 0x1 ) << 18 )
#define SYSCFG_SWPR_P18WP_MASK SYSCFG_SWPR_P18WP(ALL1)
#define SYSCFG_SWPR_P19WP(v) ( ( (v) & 0x1 ) << 19 )
#define SYSCFG_SWPR_P19WP_MASK SYSCFG_SWPR_P19WP(ALL1)
#define SYSCFG_SWPR_P20WP(v) ( ( (v) & 0x1 ) << 20 )
#define SYSCFG_SWPR_P20WP_MASK SYSCFG_SWPR_P20WP(ALL1)
#define SYSCFG_SWPR_P21WP(v) ( ( (v) & 0x1 ) << 21 )
#define SYSCFG_SWPR_P21WP_MASK SYSCFG_SWPR_P21WP(ALL1)
#define SYSCFG_SWPR_P22WP(v) ( ( (v) & 0x1 ) << 22 )
#define SYSCFG_SWPR_P22WP_MASK SYSCFG_SWPR_P22WP(ALL1)
#define SYSCFG_SWPR_P23WP(v) ( ( (v) & 0x1 ) << 23 )
#define SYSCFG_SWPR_P23WP_MASK SYSCFG_SWPR_P23WP(ALL1)
#define SYSCFG_SWPR_P24WP(v) ( ( (v) & 0x1 ) << 24 )
#define SYSCFG_SWPR_P24WP_MASK SYSCFG_SWPR_P24WP(ALL1)
#define SYSCFG_SWPR_P25WP(v) ( ( (v) & 0x1 ) << 25 )
#define SYSCFG_SWPR_P25WP_MASK SYSCFG_SWPR_P25WP(ALL1)
#define SYSCFG_SWPR_P26WP(v) ( ( (v) & 0x1 ) << 26 )
#define SYSCFG_SWPR_P26WP_MASK SYSCFG_SWPR_P26WP(ALL1)
#define SYSCFG_SWPR_P27WP(v) ( ( (v) & 0x1 ) << 27 )
#define SYSCFG_SWPR_P27WP_MASK SYSCFG_SWPR_P27WP(ALL1)
#define SYSCFG_SWPR_P28WP(v) ( ( (v) & 0x1 ) << 28 )
#define SYSCFG_SWPR_P28WP_MASK SYSCFG_SWPR_P28WP(ALL1)
#define SYSCFG_SWPR_P29WP(v) ( ( (v) & 0x1 ) << 29 )
#define SYSCFG_SWPR_P29WP_MASK SYSCFG_SWPR_P29WP(ALL1)
#define SYSCFG_SWPR_P30WP(v) ( ( (v) & 0x1 ) << 30 )
#define SYSCFG_SWPR_P30WP_MASK SYSCFG_SWPR_P30WP(ALL1)
#define SYSCFG_SWPR_P31WP(v) ( ( (v) & 0x1 ) << 31 )
#define SYSCFG_SWPR_P31WP_MASK SYSCFG_SWPR_P31WP(ALL1)

/* SYSCFG SKR register as macros */

#define SYSCFG_SKR_KEY(v) ( ( (v) & 0xFF ) << 0 )
#define SYSCFG_SKR_KEY_MASK SYSCFG_SKR_KEY(ALL1)

#endif

